const clientKey=localStorage.getItem('mlr-auto-client')||crypto.randomUUID();
localStorage.setItem('mlr-auto-client',clientKey);

const BLOCKED=[[-3,1,-4,1],[11,18,-10,-3]];
const insideBlock=(x,z)=>BLOCKED.some(([x1,x2,z1,z2])=>x>=x1&&x<=x2&&z>=z1&&z<=z2);
const key=(x,z)=>`${x},${z}`;
const heuristic=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.z-b.z);

export function findAutoQuestPath(start,target){
  const snap=p=>({x:Math.max(-32,Math.min(32,Math.round(p.x))),z:Math.max(-32,Math.min(32,Math.round(p.z)))});
  const from=snap(start),to=snap(target),open=[from],came=new Map(),g=new Map([[key(from.x,from.z),0]]),seen=new Set();
  while(open.length){open.sort((a,b)=>(g.get(key(a.x,a.z))+heuristic(a,to))-(g.get(key(b.x,b.z))+heuristic(b,to)));const cur=open.shift(),ck=key(cur.x,cur.z);if(seen.has(ck))continue;seen.add(ck);if(cur.x===to.x&&cur.z===to.z){const path=[cur];let k=ck;while(came.has(k)){const p=came.get(k);path.push(p);k=key(p.x,p.z);}return path.reverse().filter((_,i)=>i===0||i%2===0||i===path.length-1);}
    for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const n={x:cur.x+dx,z:cur.z+dz},nk=key(n.x,n.z);if(Math.abs(n.x)>32||Math.abs(n.z)>32||insideBlock(n.x,n.z)||seen.has(nk))continue;const score=(g.get(ck)||0)+1;if(score<(g.get(nk)??Infinity)){g.set(nk,score);came.set(nk,cur);open.push(n);}}
  }return [from,to];
}

export function initializeAutoQuest({getPosition,getZone,api,onWarp,onMessage,onReward}){
  const ui=document.createElement('section');ui.id='autoQuestPanel';ui.innerHTML=`<button id="autoQuestToggle" title="เดินเควสอัตโนมัติ">🧭 เควสออโต้</button><div id="autoQuestBody" class="aq-hidden"><div class="aq-head"><b>🧭 เดินเควสอัตโนมัติ</b><button id="aqClose">×</button></div><select id="aqSelect"></select><div id="aqDescription">กำลังโหลดเควส…</div><div id="aqStatus">สถานะ: หยุด</div><div class="aq-actions"><button id="aqStart">เริ่มเดิน</button><button id="aqPause">หยุด</button></div></div>`;document.body.append(ui);
  const body=ui.querySelector('#autoQuestBody'),select=ui.querySelector('#aqSelect'),description=ui.querySelector('#aqDescription'),status=ui.querySelector('#aqStatus');
  let quests=[],session=null,objective=null,running=false,path=[],pathIndex=0,lastBeat=0,lastDistance=Infinity,stuckFor=0,stuckRetries=0,busy=false,combatBusy=false;
  const parseObjective=value=>{try{return typeof value==='string'?JSON.parse(value):value;}catch{return null;}};
  const setStatus=text=>status.textContent=`สถานะ: ${text}`;
  const rebuildPath=()=>{const p=getPosition();path=findAutoQuestPath(p,objective);pathIndex=Math.min(1,path.length-1);lastDistance=Infinity;};
  async function ensureObjectiveZone(){if(!objective||getZone()===objective.zone)return;const warp=await api.warp(session.sessionId);if(!warp.ok)throw new Error(warp.message||'วาร์ปไปแมพเควสไม่สำเร็จ');onWarp?.(warp.zone,Number(warp.x)||0,Number(warp.z)||5);objective=parseObjective(warp.objectiveJson)||objective;if(getZone()!==objective.zone)throw new Error(`ไม่สามารถเข้าแมพ ${objective.zone}`);setStatus(`วาร์ปแล้ว • กำลังไป: ${objective.label}`);}
  async function load(){try{const data=await api.list();quests=data.quests||[];select.innerHTML=quests.map(q=>`<option value="${q.id}">${q.name}</option>`).join('');const active=data.active;if(active?.success){session=active;objective=parseObjective(active.objectiveJson);setStatus(`พักอยู่ • ${objective?.label||'รอรับรางวัล'}`);}select.onchange=()=>{const q=quests.find(x=>x.id===select.value);description.textContent=q?.description||'';};select.onchange();}catch{setStatus('เชื่อมต่อเซิร์ฟเวอร์ไม่ได้');}}
  async function start(){if(busy)return;busy=true;try{if(!session||session.status==='CLAIMED'){const p=getPosition(),r=await api.start(select.value,clientKey,getZone(),p.x,p.z);if(!r.ok)throw new Error(r.message);session=r;}objective=parseObjective(session.objectiveJson);if(session.status==='COMPLETED')return claim();if(!objective)throw new Error('ไม่มีเป้าหมายเควส');await ensureObjectiveZone();rebuildPath();running=true;stuckFor=0;stuckRetries=0;setStatus(`กำลังไป: ${objective.label}`);onMessage?.(`🧭 เริ่มออโต้: ${objective.label}`);}catch(e){setStatus(e.message);}finally{busy=false;}}
  function pause(reason='ผู้เล่นหยุด'){running=false;setStatus(reason);}
  async function claim(){if(!session)return;const r=await api.claim(session.sessionId);if(!r.ok)throw new Error(r.message);running=false;session=null;objective=null;setStatus(r.message);onReward?.(r);onMessage?.(`🎁 ${r.message}`);await load();}
  async function advance(pos){if(busy||!session||!objective)return;busy=true;try{const r=await api.advance(session.sessionId,objective.id,getZone(),pos.x,pos.z);if(!r.ok)throw new Error(r.message);session=r;objective=parseObjective(r.objectiveJson);if(r.status==='COMPLETED'){setStatus('ครบแล้ว กำลังรับรางวัล');await claim();return;}await ensureObjectiveZone();rebuildPath();setStatus(`กำลังไป: ${objective.label}`);}catch(e){pause(e.message);}finally{busy=false;}}
  async function heartbeat(pos){if(!session)return;try{const r=await api.heartbeat(session.sessionId,getZone(),pos.x,pos.z);if(!r.ok)pause(r.message);}catch{pause('การเชื่อมต่อขาดหาย กดเริ่มเพื่อทำต่อ');}}
  async function fight(pos){if(combatBusy||!running)return;combatBusy=true;try{const required=Math.max(1,Number(objective.count)||1),enemy=objective.target||'quest_enemy';for(let defeated=0;defeated<required&&running;defeated++){let combat=await api.combatStart(session.sessionId,objective.id,enemy);if(!combat.ok)throw new Error(combat.message);setStatus(`กำลังต่อสู้ ${enemy} • HP ${combat.enemyHp}/${combat.enemyMaxHp}`);while(combat.status==='ACTIVE'&&running){await new Promise(r=>setTimeout(r,760));combat=await api.combatAttack(combat.combatId,'basic');if(!combat.ok)throw new Error(combat.message);setStatus(`ต่อสู้ ${enemy} • HP ${combat.enemyHp}/${combat.enemyMaxHp} • ${defeated}/${required}`);}}if(running)await advance(pos);}catch(e){pause(e.message);}finally{combatBusy=false;}}
  function tick(dt,manualMoving=false){if(!running||!objective)return null;if(manualMoving){pause('พัก: ผู้เล่นควบคุมเอง');return null;}const pos=getPosition();if(getZone()!==objective.zone){pause('หยุด: อยู่คนละโซนกับเป้าหมาย');return null;}const now=performance.now();if(now-lastBeat>1000){lastBeat=now;heartbeat(pos);}const waypoint=path[pathIndex]||objective,dx=waypoint.x-pos.x,dz=waypoint.z-pos.z,d=Math.hypot(dx,dz);if(d<.65&&pathIndex<path.length-1){pathIndex++;lastDistance=Infinity;return null;}const finalDistance=Math.hypot(objective.x-pos.x,objective.z-pos.z);if(finalDistance<1.8){if(objective.type==='KILL')fight(pos);else advance(pos);return null;}if(d>lastDistance-.08)stuckFor+=dt;else stuckFor=0;lastDistance=d;if(stuckFor>2.5){stuckFor=0;stuckRetries++;if(stuckRetries>=3){pause('หยุด: ติดสิ่งกีดขวาง กรุณาขยับแล้วเริ่มใหม่');return null;}rebuildPath();setStatus(`คำนวณเส้นทางใหม่ ${stuckRetries}/3`);return null;}return d>.01?{x:dx/d,z:dz/d}:null;}
  ui.querySelector('#autoQuestToggle').onclick=()=>{const opening=body.classList.contains('aq-hidden');if(opening)dispatchEvent(new CustomEvent('monsterlife-panel-open',{detail:{panel:'autoQuest'}}));body.classList.toggle('aq-hidden');};addEventListener('monsterlife-panel-open',event=>{if(event.detail?.panel!=='autoQuest')body.classList.add('aq-hidden');});ui.querySelector('#aqClose').onclick=()=>body.classList.add('aq-hidden');ui.querySelector('#aqStart').onclick=start;ui.querySelector('#aqPause').onclick=()=>pause();load();
  return{tick,start,pause,reload:load,get running(){return running;}};
}
