import { CONTENT_PROVENANCE, assertContentProvenance } from './content-provenance.mjs';
import { CONTENT_ID_PATTERNS, CONTENT_STATES, LEARNSET_METHODS } from './content-validation.mjs';
import { MONSTER_CATALOG } from './monster-catalog.mjs';
import { skillCatalogEntry } from './skill-catalog.mjs';

assertContentProvenance(CONTENT_PROVENANCE);

const TYPE_MAP = Object.freeze({
  "NORMAL": "Normal",
  "FIRE": "Fire",
  "WATER": "Water",
  "GRASS": "Grass",
  "ELECTRIC": "Electric",
  "ICE": "Ice",
  "ROCK": "Rock",
  "GROUND": "Ground",
  "FLYING": "Flying",
  "POISON": "Poison",
  "DARK": "Dark",
  "LIGHT": "Fairy",
  "PSYCHIC": "Psychic",
  "BUG": "Bug",
  "DRAGON": "Dragon",
  "FIGHTING": "Fighting",
  "STEEL": "Steel",
  "GHOST": "Ghost",
});

const RAW_LEARNSET = [
  ["LE_0001","MON_001|SK_NORMAL_01","MON_001","SP_NORMAL_SLIME",1,"SK_NORMAL_01","NORMAL","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Level >= 1","Core Stage1 learnset","OK"],
  ["LE_0002","MON_001|SK_NORMAL_02","MON_001","SP_NORMAL_SLIME",1,"SK_NORMAL_02","NORMAL","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Level >= 5","Core Stage1 learnset","OK"],
  ["LE_0003","MON_001|SK_NORMAL_03","MON_001","SP_NORMAL_SLIME",1,"SK_NORMAL_03","NORMAL","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Level >= 8","Core Stage1 learnset","OK"],
  ["LE_0004","MON_001|SK_NORMAL_04","MON_001","SP_NORMAL_SLIME",1,"SK_NORMAL_04","NORMAL","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Level >= 10","Core Stage1 learnset","OK"],
  ["LE_0005","MON_001|SK_NORMAL_05","MON_001","SP_NORMAL_SLIME",1,"SK_NORMAL_05","NORMAL","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Level >= 14","Core Stage1 learnset","OK"],
  ["LE_0006","MON_019|SK_NORMAL_01","MON_019","SP_NORMAL_BEAST",2,"SK_NORMAL_01","NORMAL","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Historical level >= 1; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0007","MON_019|SK_NORMAL_02","MON_019","SP_NORMAL_BEAST",2,"SK_NORMAL_02","NORMAL","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Historical level >= 5; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0008","MON_019|SK_NORMAL_03","MON_019","SP_NORMAL_BEAST",2,"SK_NORMAL_03","NORMAL","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Historical level >= 8; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0009","MON_019|SK_NORMAL_04","MON_019","SP_NORMAL_BEAST",2,"SK_NORMAL_04","NORMAL","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Historical level >= 10; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0010","MON_019|SK_NORMAL_05","MON_019","SP_NORMAL_BEAST",2,"SK_NORMAL_05","NORMAL","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Historical level >= 14; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0011","MON_019|SK_NORMAL_06","MON_019","SP_NORMAL_BEAST",2,"SK_NORMAL_06","NORMAL","Evolution",15,2,null,0,"EVO_MON_019",true,true,true,"Active",98,"Evolution into this Stage2 form OR captured Stage2 move generation","Signature high-impact move; limited Uses","OK"],
  ["LE_0012","MON_019|SK_FIGHTING_01","MON_019","SP_NORMAL_BEAST",2,"SK_FIGHTING_01","FIGHTING","SecondaryLevel",18,2,"FIGHTING",0,null,true,true,true,"Active",82,"Level >= 18 AND SecondaryType = FIGHTING","Secondary-type basic/offensive technique","OK"],
  ["LE_0013","MON_019|SK_FIGHTING_03","MON_019","SP_NORMAL_BEAST",2,"SK_FIGHTING_03","FIGHTING","SecondaryLevel",30,2,"FIGHTING",0,null,true,true,true,"Active",76,"Level >= 30 AND SecondaryType = FIGHTING","Secondary-type utility/defensive technique","OK"],
  ["LE_0014","MON_019|SK_FLYING_01","MON_019","SP_NORMAL_BEAST",2,"SK_FLYING_01","FLYING","SecondaryLevel",20,2,"FLYING",0,null,true,true,true,"Active",82,"Level >= 20 AND SecondaryType = FLYING","Secondary-type basic/offensive technique","OK"],
  ["LE_0015","MON_019|SK_FLYING_03","MON_019","SP_NORMAL_BEAST",2,"SK_FLYING_03","FLYING","SecondaryLevel",32,2,"FLYING",0,null,true,true,true,"Active",76,"Level >= 32 AND SecondaryType = FLYING","Secondary-type utility/defensive technique","OK"],
  ["LE_0016","MON_019|SK_PSYCHIC_01","MON_019","SP_NORMAL_BEAST",2,"SK_PSYCHIC_01","PSYCHIC","SecondaryLevel",22,2,"PSYCHIC",0,null,true,true,true,"Active",82,"Level >= 22 AND SecondaryType = PSYCHIC","Secondary-type basic/offensive technique","OK"],
  ["LE_0017","MON_019|SK_PSYCHIC_03","MON_019","SP_NORMAL_BEAST",2,"SK_PSYCHIC_03","PSYCHIC","SecondaryLevel",34,2,"PSYCHIC",0,null,true,true,true,"Active",76,"Level >= 34 AND SecondaryType = PSYCHIC","Secondary-type utility/defensive technique","OK"],
  ["LE_0018","MON_019|SK_STEEL_03","MON_019","SP_NORMAL_BEAST",2,"SK_STEEL_03","STEEL","Tutor",20,2,null,40,"TUTOR_BALANCED_1",false,true,true,"Active",69,"Level >= 20 AND Bond >= 40","Role tutor for Balanced build","OK"],
  ["LE_0019","MON_019|SK_PSYCHIC_02","MON_019","SP_NORMAL_BEAST",2,"SK_PSYCHIC_02","PSYCHIC","Tutor",28,2,null,60,"TUTOR_BALANCED_2",false,true,true,"Active",68,"Level >= 28 AND Bond >= 60","Role tutor for Balanced build","OK"],
  ["LE_0020","MON_019|SK_FLYING_02","MON_019","SP_NORMAL_BEAST",2,"SK_FLYING_02","FLYING","BreedingCandidate",1,2,"FLYING",0,"BREED_SP_NORMAL_BEAST",false,true,true,"DataReady",50,"Egg inheritance candidate; target SecondaryType must allow FLYING","BRD_v1.0 Skill Memory candidate; inherited from partner, not auto-equippable at hatch.","OK"],
  ["LE_0021","MON_019|SK_PSYCHIC_04","MON_019","SP_NORMAL_BEAST",2,"SK_PSYCHIC_04","PSYCHIC","RareManual",30,2,"PSYCHIC",60,"MANUAL_SK_PSYCHIC_04",false,true,true,"Deferred",40,"Level >= 30 AND Bond >= 60 AND SecondaryType = PSYCHIC","Manual source becomes active after Item_Master Fix #12","OK"],
  ["LE_0022","MON_002|SK_FIRE_01","MON_002","SP_FIRE_SLIME",1,"SK_FIRE_01","FIRE","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Level >= 1","Core Stage1 learnset","OK"],
  ["LE_0023","MON_002|SK_FIRE_02","MON_002","SP_FIRE_SLIME",1,"SK_FIRE_02","FIRE","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Level >= 5","Core Stage1 learnset","OK"],
  ["LE_0024","MON_002|SK_FIRE_03","MON_002","SP_FIRE_SLIME",1,"SK_FIRE_03","FIRE","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Level >= 8","Core Stage1 learnset","OK"],
  ["LE_0025","MON_002|SK_FIRE_04","MON_002","SP_FIRE_SLIME",1,"SK_FIRE_04","FIRE","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Level >= 10","Core Stage1 learnset","OK"],
  ["LE_0026","MON_002|SK_FIRE_05","MON_002","SP_FIRE_SLIME",1,"SK_FIRE_05","FIRE","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Level >= 14","Core Stage1 learnset","OK"],
  ["LE_0027","MON_020|SK_FIRE_01","MON_020","SP_FIRE_BEAST",2,"SK_FIRE_01","FIRE","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Historical level >= 1; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0028","MON_020|SK_FIRE_02","MON_020","SP_FIRE_BEAST",2,"SK_FIRE_02","FIRE","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Historical level >= 5; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0029","MON_020|SK_FIRE_03","MON_020","SP_FIRE_BEAST",2,"SK_FIRE_03","FIRE","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Historical level >= 8; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0030","MON_020|SK_FIRE_04","MON_020","SP_FIRE_BEAST",2,"SK_FIRE_04","FIRE","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Historical level >= 10; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0031","MON_020|SK_FIRE_05","MON_020","SP_FIRE_BEAST",2,"SK_FIRE_05","FIRE","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Historical level >= 14; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0032","MON_020|SK_FIRE_06","MON_020","SP_FIRE_BEAST",2,"SK_FIRE_06","FIRE","Evolution",15,2,null,0,"EVO_MON_020",true,true,true,"Active",98,"Evolution into this Stage2 form OR captured Stage2 move generation","Signature high-impact move; limited Uses","OK"],
  ["LE_0033","MON_020|SK_DRAGON_01","MON_020","SP_FIRE_BEAST",2,"SK_DRAGON_01","DRAGON","SecondaryLevel",18,2,"DRAGON",0,null,true,true,true,"Active",82,"Level >= 18 AND SecondaryType = DRAGON","Secondary-type basic/offensive technique","OK"],
  ["LE_0034","MON_020|SK_DRAGON_03","MON_020","SP_FIRE_BEAST",2,"SK_DRAGON_03","DRAGON","SecondaryLevel",30,2,"DRAGON",0,null,true,true,true,"Active",76,"Level >= 30 AND SecondaryType = DRAGON","Secondary-type utility/defensive technique","OK"],
  ["LE_0035","MON_020|SK_DARK_01","MON_020","SP_FIRE_BEAST",2,"SK_DARK_01","DARK","SecondaryLevel",20,2,"DARK",0,null,true,true,true,"Active",82,"Level >= 20 AND SecondaryType = DARK","Secondary-type basic/offensive technique","OK"],
  ["LE_0036","MON_020|SK_DARK_03","MON_020","SP_FIRE_BEAST",2,"SK_DARK_03","DARK","SecondaryLevel",32,2,"DARK",0,null,true,true,true,"Active",76,"Level >= 32 AND SecondaryType = DARK","Secondary-type utility/defensive technique","OK"],
  ["LE_0037","MON_020|SK_FIGHTING_01","MON_020","SP_FIRE_BEAST",2,"SK_FIGHTING_01","FIGHTING","SecondaryLevel",22,2,"FIGHTING",0,null,true,true,true,"Active",82,"Level >= 22 AND SecondaryType = FIGHTING","Secondary-type basic/offensive technique","OK"],
  ["LE_0038","MON_020|SK_FIGHTING_03","MON_020","SP_FIRE_BEAST",2,"SK_FIGHTING_03","FIGHTING","SecondaryLevel",34,2,"FIGHTING",0,null,true,true,true,"Active",76,"Level >= 34 AND SecondaryType = FIGHTING","Secondary-type utility/defensive technique","OK"],
  ["LE_0039","MON_020|SK_NORMAL_05","MON_020","SP_FIRE_BEAST",2,"SK_NORMAL_05","NORMAL","Tutor",20,2,null,40,"TUTOR_BURST_1",false,true,true,"Active",69,"Level >= 20 AND Bond >= 40","Role tutor for Burst build","OK"],
  ["LE_0040","MON_020|SK_DARK_02","MON_020","SP_FIRE_BEAST",2,"SK_DARK_02","DARK","Tutor",28,2,null,60,"TUTOR_BURST_2",false,true,true,"Active",68,"Level >= 28 AND Bond >= 60","Role tutor for Burst build","OK"],
  ["LE_0041","MON_020|SK_FIGHTING_04","MON_020","SP_FIRE_BEAST",2,"SK_FIGHTING_04","FIGHTING","RareManual",30,2,"FIGHTING",60,"MANUAL_SK_FIGHTING_04",false,true,true,"Deferred",40,"Level >= 30 AND Bond >= 60 AND SecondaryType = FIGHTING","Manual source becomes active after Item_Master Fix #12","OK"],
  ["LE_0042","MON_003|SK_WATER_01","MON_003","SP_WATER_SLIME",1,"SK_WATER_01","WATER","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Level >= 1","Core Stage1 learnset","OK"],
  ["LE_0043","MON_003|SK_WATER_02","MON_003","SP_WATER_SLIME",1,"SK_WATER_02","WATER","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Level >= 5","Core Stage1 learnset","OK"],
  ["LE_0044","MON_003|SK_WATER_03","MON_003","SP_WATER_SLIME",1,"SK_WATER_03","WATER","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Level >= 8","Core Stage1 learnset","OK"],
  ["LE_0045","MON_003|SK_WATER_04","MON_003","SP_WATER_SLIME",1,"SK_WATER_04","WATER","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Level >= 10","Core Stage1 learnset","OK"],
  ["LE_0046","MON_003|SK_WATER_05","MON_003","SP_WATER_SLIME",1,"SK_WATER_05","WATER","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Level >= 14","Core Stage1 learnset","OK"],
  ["LE_0047","MON_021|SK_WATER_01","MON_021","SP_WATER_BEAST",2,"SK_WATER_01","WATER","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Historical level >= 1; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0048","MON_021|SK_WATER_02","MON_021","SP_WATER_BEAST",2,"SK_WATER_02","WATER","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Historical level >= 5; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0049","MON_021|SK_WATER_03","MON_021","SP_WATER_BEAST",2,"SK_WATER_03","WATER","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Historical level >= 8; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0050","MON_021|SK_WATER_04","MON_021","SP_WATER_BEAST",2,"SK_WATER_04","WATER","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Historical level >= 10; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0051","MON_021|SK_WATER_05","MON_021","SP_WATER_BEAST",2,"SK_WATER_05","WATER","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Historical level >= 14; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0052","MON_021|SK_WATER_06","MON_021","SP_WATER_BEAST",2,"SK_WATER_06","WATER","Evolution",15,2,null,0,"EVO_MON_021",true,true,true,"Active",98,"Evolution into this Stage2 form OR captured Stage2 move generation","Signature high-impact move; limited Uses","OK"],
  ["LE_0053","MON_021|SK_ICE_01","MON_021","SP_WATER_BEAST",2,"SK_ICE_01","ICE","SecondaryLevel",18,2,"ICE",0,null,true,true,true,"Active",82,"Level >= 18 AND SecondaryType = ICE","Secondary-type basic/offensive technique","OK"],
  ["LE_0054","MON_021|SK_ICE_03","MON_021","SP_WATER_BEAST",2,"SK_ICE_03","ICE","SecondaryLevel",30,2,"ICE",0,null,true,true,true,"Active",76,"Level >= 30 AND SecondaryType = ICE","Secondary-type utility/defensive technique","OK"],
  ["LE_0055","MON_021|SK_PSYCHIC_01","MON_021","SP_WATER_BEAST",2,"SK_PSYCHIC_01","PSYCHIC","SecondaryLevel",20,2,"PSYCHIC",0,null,true,true,true,"Active",82,"Level >= 20 AND SecondaryType = PSYCHIC","Secondary-type basic/offensive technique","OK"],
  ["LE_0056","MON_021|SK_PSYCHIC_03","MON_021","SP_WATER_BEAST",2,"SK_PSYCHIC_03","PSYCHIC","SecondaryLevel",32,2,"PSYCHIC",0,null,true,true,true,"Active",76,"Level >= 32 AND SecondaryType = PSYCHIC","Secondary-type utility/defensive technique","OK"],
  ["LE_0057","MON_021|SK_POISON_01","MON_021","SP_WATER_BEAST",2,"SK_POISON_01","POISON","SecondaryLevel",22,2,"POISON",0,null,true,true,true,"Active",82,"Level >= 22 AND SecondaryType = POISON","Secondary-type basic/offensive technique","OK"],
  ["LE_0058","MON_021|SK_POISON_03","MON_021","SP_WATER_BEAST",2,"SK_POISON_03","POISON","SecondaryLevel",34,2,"POISON",0,null,true,true,true,"Active",76,"Level >= 34 AND SecondaryType = POISON","Secondary-type utility/defensive technique","OK"],
  ["LE_0059","MON_021|SK_LIGHT_04","MON_021","SP_WATER_BEAST",2,"SK_LIGHT_04","LIGHT","Tutor",20,2,null,40,"TUTOR_SUSTAIN_1",false,true,true,"Active",69,"Level >= 20 AND Bond >= 40","Role tutor for Sustain build","OK"],
  ["LE_0060","MON_021|SK_NORMAL_03","MON_021","SP_WATER_BEAST",2,"SK_NORMAL_03","NORMAL","Tutor",28,2,null,60,"TUTOR_SUSTAIN_2",false,true,true,"Active",68,"Level >= 28 AND Bond >= 60","Role tutor for Sustain build","OK"],
  ["LE_0061","MON_021|SK_PSYCHIC_02","MON_021","SP_WATER_BEAST",2,"SK_PSYCHIC_02","PSYCHIC","BreedingCandidate",1,2,"PSYCHIC",0,"BREED_SP_WATER_BEAST",false,true,true,"DataReady",50,"Egg inheritance candidate; target SecondaryType must allow PSYCHIC","BRD_v1.0 Skill Memory candidate; inherited from partner, not auto-equippable at hatch.","OK"],
  ["LE_0062","MON_021|SK_POISON_04","MON_021","SP_WATER_BEAST",2,"SK_POISON_04","POISON","RareManual",30,2,"POISON",60,"MANUAL_SK_POISON_04",false,true,true,"Deferred",40,"Level >= 30 AND Bond >= 60 AND SecondaryType = POISON","Manual source becomes active after Item_Master Fix #12","OK"],
  ["LE_0063","MON_004|SK_GRASS_01","MON_004","SP_GRASS_SLIME",1,"SK_GRASS_01","GRASS","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Level >= 1","Core Stage1 learnset","OK"],
  ["LE_0064","MON_004|SK_GRASS_02","MON_004","SP_GRASS_SLIME",1,"SK_GRASS_02","GRASS","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Level >= 5","Core Stage1 learnset","OK"],
  ["LE_0065","MON_004|SK_GRASS_03","MON_004","SP_GRASS_SLIME",1,"SK_GRASS_03","GRASS","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Level >= 8","Core Stage1 learnset","OK"],
  ["LE_0066","MON_004|SK_GRASS_04","MON_004","SP_GRASS_SLIME",1,"SK_GRASS_04","GRASS","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Level >= 10","Core Stage1 learnset","OK"],
  ["LE_0067","MON_004|SK_GRASS_05","MON_004","SP_GRASS_SLIME",1,"SK_GRASS_05","GRASS","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Level >= 14","Core Stage1 learnset","OK"],
  ["LE_0068","MON_022|SK_GRASS_01","MON_022","SP_GRASS_BEAST",2,"SK_GRASS_01","GRASS","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Historical level >= 1; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0069","MON_022|SK_GRASS_02","MON_022","SP_GRASS_BEAST",2,"SK_GRASS_02","GRASS","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Historical level >= 5; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0070","MON_022|SK_GRASS_03","MON_022","SP_GRASS_BEAST",2,"SK_GRASS_03","GRASS","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Historical level >= 8; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0071","MON_022|SK_GRASS_04","MON_022","SP_GRASS_BEAST",2,"SK_GRASS_04","GRASS","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Historical level >= 10; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0072","MON_022|SK_GRASS_05","MON_022","SP_GRASS_BEAST",2,"SK_GRASS_05","GRASS","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Historical level >= 14; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0073","MON_022|SK_GRASS_06","MON_022","SP_GRASS_BEAST",2,"SK_GRASS_06","GRASS","Evolution",15,2,null,0,"EVO_MON_022",true,true,true,"Active",98,"Evolution into this Stage2 form OR captured Stage2 move generation","Signature high-impact move; limited Uses","OK"],
  ["LE_0074","MON_022|SK_POISON_01","MON_022","SP_GRASS_BEAST",2,"SK_POISON_01","POISON","SecondaryLevel",18,2,"POISON",0,null,true,true,true,"Active",82,"Level >= 18 AND SecondaryType = POISON","Secondary-type basic/offensive technique","OK"],
  ["LE_0075","MON_022|SK_POISON_03","MON_022","SP_GRASS_BEAST",2,"SK_POISON_03","POISON","SecondaryLevel",30,2,"POISON",0,null,true,true,true,"Active",76,"Level >= 30 AND SecondaryType = POISON","Secondary-type utility/defensive technique","OK"],
  ["LE_0076","MON_022|SK_BUG_01","MON_022","SP_GRASS_BEAST",2,"SK_BUG_01","BUG","SecondaryLevel",20,2,"BUG",0,null,true,true,true,"Active",82,"Level >= 20 AND SecondaryType = BUG","Secondary-type basic/offensive technique","OK"],
  ["LE_0077","MON_022|SK_BUG_03","MON_022","SP_GRASS_BEAST",2,"SK_BUG_03","BUG","SecondaryLevel",32,2,"BUG",0,null,true,true,true,"Active",76,"Level >= 32 AND SecondaryType = BUG","Secondary-type utility/defensive technique","OK"],
  ["LE_0078","MON_022|SK_LIGHT_01","MON_022","SP_GRASS_BEAST",2,"SK_LIGHT_01","LIGHT","SecondaryLevel",22,2,"LIGHT",0,null,true,true,true,"Active",82,"Level >= 22 AND SecondaryType = LIGHT","Secondary-type basic/offensive technique","OK"],
  ["LE_0079","MON_022|SK_LIGHT_03","MON_022","SP_GRASS_BEAST",2,"SK_LIGHT_03","LIGHT","SecondaryLevel",34,2,"LIGHT",0,null,true,true,true,"Active",76,"Level >= 34 AND SecondaryType = LIGHT","Secondary-type utility/defensive technique","OK"],
  ["LE_0080","MON_022|SK_LIGHT_04","MON_022","SP_GRASS_BEAST",2,"SK_LIGHT_04","LIGHT","Tutor",20,2,null,40,"TUTOR_SUPPORT_1",false,true,true,"Active",69,"Level >= 20 AND Bond >= 40","Role tutor for Support build","OK"],
  ["LE_0081","MON_022|SK_STEEL_03","MON_022","SP_GRASS_BEAST",2,"SK_STEEL_03","STEEL","Tutor",28,2,null,60,"TUTOR_SUPPORT_2",false,true,true,"Active",68,"Level >= 28 AND Bond >= 60","Role tutor for Support build","OK"],
  ["LE_0082","MON_022|SK_BUG_02","MON_022","SP_GRASS_BEAST",2,"SK_BUG_02","BUG","BreedingCandidate",1,2,"BUG",0,"BREED_SP_GRASS_BEAST",false,true,true,"DataReady",50,"Egg inheritance candidate; target SecondaryType must allow BUG","BRD_v1.0 Skill Memory candidate; inherited from partner, not auto-equippable at hatch.","OK"],
  ["LE_0083","MON_005|SK_ELECTRIC_01","MON_005","SP_ELECTRIC_SLIME",1,"SK_ELECTRIC_01","ELECTRIC","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Level >= 1","Core Stage1 learnset","OK"],
  ["LE_0084","MON_005|SK_ELECTRIC_02","MON_005","SP_ELECTRIC_SLIME",1,"SK_ELECTRIC_02","ELECTRIC","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Level >= 5","Core Stage1 learnset","OK"],
  ["LE_0085","MON_005|SK_ELECTRIC_03","MON_005","SP_ELECTRIC_SLIME",1,"SK_ELECTRIC_03","ELECTRIC","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Level >= 8","Core Stage1 learnset","OK"],
  ["LE_0086","MON_005|SK_ELECTRIC_04","MON_005","SP_ELECTRIC_SLIME",1,"SK_ELECTRIC_04","ELECTRIC","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Level >= 10","Core Stage1 learnset","OK"],
  ["LE_0087","MON_005|SK_ELECTRIC_05","MON_005","SP_ELECTRIC_SLIME",1,"SK_ELECTRIC_05","ELECTRIC","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Level >= 14","Core Stage1 learnset","OK"],
  ["LE_0088","MON_023|SK_ELECTRIC_01","MON_023","SP_ELECTRIC_BEAST",2,"SK_ELECTRIC_01","ELECTRIC","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Historical level >= 1; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0089","MON_023|SK_ELECTRIC_02","MON_023","SP_ELECTRIC_BEAST",2,"SK_ELECTRIC_02","ELECTRIC","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Historical level >= 5; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0090","MON_023|SK_ELECTRIC_03","MON_023","SP_ELECTRIC_BEAST",2,"SK_ELECTRIC_03","ELECTRIC","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Historical level >= 8; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0091","MON_023|SK_ELECTRIC_04","MON_023","SP_ELECTRIC_BEAST",2,"SK_ELECTRIC_04","ELECTRIC","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Historical level >= 10; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0092","MON_023|SK_ELECTRIC_05","MON_023","SP_ELECTRIC_BEAST",2,"SK_ELECTRIC_05","ELECTRIC","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Historical level >= 14; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0093","MON_023|SK_ELECTRIC_06","MON_023","SP_ELECTRIC_BEAST",2,"SK_ELECTRIC_06","ELECTRIC","Evolution",15,2,null,0,"EVO_MON_023",true,true,true,"Active",98,"Evolution into this Stage2 form OR captured Stage2 move generation","Signature high-impact move; limited Uses","OK"],
  ["LE_0094","MON_023|SK_STEEL_01","MON_023","SP_ELECTRIC_BEAST",2,"SK_STEEL_01","STEEL","SecondaryLevel",18,2,"STEEL",0,null,true,true,true,"Active",82,"Level >= 18 AND SecondaryType = STEEL","Secondary-type basic/offensive technique","OK"],
  ["LE_0095","MON_023|SK_STEEL_03","MON_023","SP_ELECTRIC_BEAST",2,"SK_STEEL_03","STEEL","SecondaryLevel",30,2,"STEEL",0,null,true,true,true,"Active",76,"Level >= 30 AND SecondaryType = STEEL","Secondary-type utility/defensive technique","OK"],
  ["LE_0096","MON_023|SK_FLYING_01","MON_023","SP_ELECTRIC_BEAST",2,"SK_FLYING_01","FLYING","SecondaryLevel",20,2,"FLYING",0,null,true,true,true,"Active",82,"Level >= 20 AND SecondaryType = FLYING","Secondary-type basic/offensive technique","OK"],
  ["LE_0097","MON_023|SK_FLYING_03","MON_023","SP_ELECTRIC_BEAST",2,"SK_FLYING_03","FLYING","SecondaryLevel",32,2,"FLYING",0,null,true,true,true,"Active",76,"Level >= 32 AND SecondaryType = FLYING","Secondary-type utility/defensive technique","OK"],
  ["LE_0098","MON_023|SK_DARK_01","MON_023","SP_ELECTRIC_BEAST",2,"SK_DARK_01","DARK","SecondaryLevel",22,2,"DARK",0,null,true,true,true,"Active",82,"Level >= 22 AND SecondaryType = DARK","Secondary-type basic/offensive technique","OK"],
  ["LE_0099","MON_023|SK_DARK_03","MON_023","SP_ELECTRIC_BEAST",2,"SK_DARK_03","DARK","SecondaryLevel",34,2,"DARK",0,null,true,true,true,"Active",76,"Level >= 34 AND SecondaryType = DARK","Secondary-type utility/defensive technique","OK"],
  ["LE_0100","MON_023|SK_FLYING_04","MON_023","SP_ELECTRIC_BEAST",2,"SK_FLYING_04","FLYING","Tutor",20,2,null,40,"TUTOR_SPEED_1",false,true,true,"Active",69,"Level >= 20 AND Bond >= 40","Role tutor for Speed build","OK"],
  ["LE_0101","MON_023|SK_NORMAL_05","MON_023","SP_ELECTRIC_BEAST",2,"SK_NORMAL_05","NORMAL","Tutor",28,2,null,60,"TUTOR_SPEED_2",false,true,true,"Active",68,"Level >= 28 AND Bond >= 60","Role tutor for Speed build","OK"],
  ["LE_0102","MON_023|SK_FLYING_02","MON_023","SP_ELECTRIC_BEAST",2,"SK_FLYING_02","FLYING","BreedingCandidate",1,2,"FLYING",0,"BREED_SP_ELECTRIC_BEAST",false,true,true,"DataReady",50,"Egg inheritance candidate; target SecondaryType must allow FLYING","BRD_v1.0 Skill Memory candidate; inherited from partner, not auto-equippable at hatch.","OK"],
  ["LE_0103","MON_023|SK_DARK_04","MON_023","SP_ELECTRIC_BEAST",2,"SK_DARK_04","DARK","RareManual",30,2,"DARK",60,"MANUAL_SK_DARK_04",false,true,true,"Deferred",40,"Level >= 30 AND Bond >= 60 AND SecondaryType = DARK","Manual source becomes active after Item_Master Fix #12","OK"],
  ["LE_0104","MON_006|SK_ICE_01","MON_006","SP_ICE_SLIME",1,"SK_ICE_01","ICE","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Level >= 1","Core Stage1 learnset","OK"],
  ["LE_0105","MON_006|SK_ICE_02","MON_006","SP_ICE_SLIME",1,"SK_ICE_02","ICE","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Level >= 5","Core Stage1 learnset","OK"],
  ["LE_0106","MON_006|SK_ICE_03","MON_006","SP_ICE_SLIME",1,"SK_ICE_03","ICE","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Level >= 8","Core Stage1 learnset","OK"],
  ["LE_0107","MON_006|SK_ICE_04","MON_006","SP_ICE_SLIME",1,"SK_ICE_04","ICE","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Level >= 10","Core Stage1 learnset","OK"],
  ["LE_0108","MON_006|SK_ICE_05","MON_006","SP_ICE_SLIME",1,"SK_ICE_05","ICE","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Level >= 14","Core Stage1 learnset","OK"],
  ["LE_0109","MON_024|SK_ICE_01","MON_024","SP_ICE_BEAST",2,"SK_ICE_01","ICE","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Historical level >= 1; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0110","MON_024|SK_ICE_02","MON_024","SP_ICE_BEAST",2,"SK_ICE_02","ICE","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Historical level >= 5; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0111","MON_024|SK_ICE_03","MON_024","SP_ICE_BEAST",2,"SK_ICE_03","ICE","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Historical level >= 8; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0112","MON_024|SK_ICE_04","MON_024","SP_ICE_BEAST",2,"SK_ICE_04","ICE","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Historical level >= 10; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0113","MON_024|SK_ICE_05","MON_024","SP_ICE_BEAST",2,"SK_ICE_05","ICE","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Historical level >= 14; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0114","MON_024|SK_ICE_06","MON_024","SP_ICE_BEAST",2,"SK_ICE_06","ICE","Evolution",15,2,null,0,"EVO_MON_024",true,true,true,"Active",98,"Evolution into this Stage2 form OR captured Stage2 move generation","Signature high-impact move; limited Uses","OK"],
  ["LE_0115","MON_024|SK_WATER_01","MON_024","SP_ICE_BEAST",2,"SK_WATER_01","WATER","SecondaryLevel",18,2,"WATER",0,null,true,true,true,"Active",82,"Level >= 18 AND SecondaryType = WATER","Secondary-type basic/offensive technique","OK"],
  ["LE_0116","MON_024|SK_WATER_03","MON_024","SP_ICE_BEAST",2,"SK_WATER_03","WATER","SecondaryLevel",30,2,"WATER",0,null,true,true,true,"Active",76,"Level >= 30 AND SecondaryType = WATER","Secondary-type utility/defensive technique","OK"],
  ["LE_0117","MON_024|SK_GHOST_01","MON_024","SP_ICE_BEAST",2,"SK_GHOST_01","GHOST","SecondaryLevel",20,2,"GHOST",0,null,true,true,true,"Active",82,"Level >= 20 AND SecondaryType = GHOST","Secondary-type basic/offensive technique","OK"],
  ["LE_0118","MON_024|SK_GHOST_03","MON_024","SP_ICE_BEAST",2,"SK_GHOST_03","GHOST","SecondaryLevel",32,2,"GHOST",0,null,true,true,true,"Active",76,"Level >= 32 AND SecondaryType = GHOST","Secondary-type utility/defensive technique","OK"],
  ["LE_0119","MON_024|SK_STEEL_01","MON_024","SP_ICE_BEAST",2,"SK_STEEL_01","STEEL","SecondaryLevel",22,2,"STEEL",0,null,true,true,true,"Active",82,"Level >= 22 AND SecondaryType = STEEL","Secondary-type basic/offensive technique","OK"],
  ["LE_0120","MON_024|SK_STEEL_03","MON_024","SP_ICE_BEAST",2,"SK_STEEL_03","STEEL","SecondaryLevel",34,2,"STEEL",0,null,true,true,true,"Active",76,"Level >= 34 AND SecondaryType = STEEL","Secondary-type utility/defensive technique","OK"],
  ["LE_0121","MON_024|SK_PSYCHIC_02","MON_024","SP_ICE_BEAST",2,"SK_PSYCHIC_02","PSYCHIC","Tutor",20,2,null,40,"TUTOR_CONTROL_1",false,true,true,"Active",69,"Level >= 20 AND Bond >= 40","Role tutor for Control build","OK"],
  ["LE_0122","MON_024|SK_NORMAL_05","MON_024","SP_ICE_BEAST",2,"SK_NORMAL_05","NORMAL","Tutor",28,2,null,60,"TUTOR_CONTROL_2",false,true,true,"Active",68,"Level >= 28 AND Bond >= 60","Role tutor for Control build","OK"],
  ["LE_0123","MON_024|SK_GHOST_02","MON_024","SP_ICE_BEAST",2,"SK_GHOST_02","GHOST","BreedingCandidate",1,2,"GHOST",0,"BREED_SP_ICE_BEAST",false,true,true,"DataReady",50,"Egg inheritance candidate; target SecondaryType must allow GHOST","BRD_v1.0 Skill Memory candidate; inherited from partner, not auto-equippable at hatch.","OK"],
  ["LE_0124","MON_024|SK_STEEL_04","MON_024","SP_ICE_BEAST",2,"SK_STEEL_04","STEEL","RareManual",30,2,"STEEL",60,"MANUAL_SK_STEEL_04",false,true,true,"Deferred",40,"Level >= 30 AND Bond >= 60 AND SecondaryType = STEEL","Manual source becomes active after Item_Master Fix #12","OK"],
  ["LE_0125","MON_007|SK_ROCK_01","MON_007","SP_ROCK_SLIME",1,"SK_ROCK_01","ROCK","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Level >= 1","Core Stage1 learnset","OK"],
  ["LE_0126","MON_007|SK_ROCK_02","MON_007","SP_ROCK_SLIME",1,"SK_ROCK_02","ROCK","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Level >= 5","Core Stage1 learnset","OK"],
  ["LE_0127","MON_007|SK_ROCK_03","MON_007","SP_ROCK_SLIME",1,"SK_ROCK_03","ROCK","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Level >= 8","Core Stage1 learnset","OK"],
  ["LE_0128","MON_007|SK_ROCK_04","MON_007","SP_ROCK_SLIME",1,"SK_ROCK_04","ROCK","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Level >= 10","Core Stage1 learnset","OK"],
  ["LE_0129","MON_007|SK_ROCK_05","MON_007","SP_ROCK_SLIME",1,"SK_ROCK_05","ROCK","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Level >= 14","Core Stage1 learnset","OK"],
  ["LE_0130","MON_025|SK_ROCK_01","MON_025","SP_ROCK_BEAST",2,"SK_ROCK_01","ROCK","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Historical level >= 1; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0131","MON_025|SK_ROCK_02","MON_025","SP_ROCK_BEAST",2,"SK_ROCK_02","ROCK","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Historical level >= 5; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0132","MON_025|SK_ROCK_03","MON_025","SP_ROCK_BEAST",2,"SK_ROCK_03","ROCK","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Historical level >= 8; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0133","MON_025|SK_ROCK_04","MON_025","SP_ROCK_BEAST",2,"SK_ROCK_04","ROCK","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Historical level >= 10; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0134","MON_025|SK_ROCK_05","MON_025","SP_ROCK_BEAST",2,"SK_ROCK_05","ROCK","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Historical level >= 14; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0135","MON_025|SK_ROCK_06","MON_025","SP_ROCK_BEAST",2,"SK_ROCK_06","ROCK","Evolution",15,2,null,0,"EVO_MON_025",true,true,true,"Active",98,"Evolution into this Stage2 form OR captured Stage2 move generation","Signature high-impact move; limited Uses","OK"],
  ["LE_0136","MON_025|SK_GROUND_01","MON_025","SP_ROCK_BEAST",2,"SK_GROUND_01","GROUND","SecondaryLevel",18,2,"GROUND",0,null,true,true,true,"Active",82,"Level >= 18 AND SecondaryType = GROUND","Secondary-type basic/offensive technique","OK"],
  ["LE_0137","MON_025|SK_GROUND_03","MON_025","SP_ROCK_BEAST",2,"SK_GROUND_03","GROUND","SecondaryLevel",30,2,"GROUND",0,null,true,true,true,"Active",76,"Level >= 30 AND SecondaryType = GROUND","Secondary-type utility/defensive technique","OK"],
  ["LE_0138","MON_025|SK_STEEL_01","MON_025","SP_ROCK_BEAST",2,"SK_STEEL_01","STEEL","SecondaryLevel",20,2,"STEEL",0,null,true,true,true,"Active",82,"Level >= 20 AND SecondaryType = STEEL","Secondary-type basic/offensive technique","OK"],
  ["LE_0139","MON_025|SK_STEEL_03","MON_025","SP_ROCK_BEAST",2,"SK_STEEL_03","STEEL","SecondaryLevel",32,2,"STEEL",0,null,true,true,true,"Active",76,"Level >= 32 AND SecondaryType = STEEL","Secondary-type utility/defensive technique","OK"],
  ["LE_0140","MON_025|SK_FIGHTING_01","MON_025","SP_ROCK_BEAST",2,"SK_FIGHTING_01","FIGHTING","SecondaryLevel",22,2,"FIGHTING",0,null,true,true,true,"Active",82,"Level >= 22 AND SecondaryType = FIGHTING","Secondary-type basic/offensive technique","OK"],
  ["LE_0141","MON_025|SK_FIGHTING_03","MON_025","SP_ROCK_BEAST",2,"SK_FIGHTING_03","FIGHTING","SecondaryLevel",34,2,"FIGHTING",0,null,true,true,true,"Active",76,"Level >= 34 AND SecondaryType = FIGHTING","Secondary-type utility/defensive technique","OK"],
  ["LE_0142","MON_025|SK_NORMAL_03","MON_025","SP_ROCK_BEAST",2,"SK_NORMAL_03","NORMAL","Tutor",20,2,null,40,"TUTOR_TANK_1",false,true,true,"Active",69,"Level >= 20 AND Bond >= 40","Role tutor for Tank build","OK"],
  ["LE_0143","MON_025|SK_STEEL_02","MON_025","SP_ROCK_BEAST",2,"SK_STEEL_02","STEEL","BreedingCandidate",1,2,"STEEL",0,"BREED_SP_ROCK_BEAST",false,true,true,"DataReady",50,"Egg inheritance candidate; target SecondaryType must allow STEEL","BRD_v1.0 Skill Memory candidate; inherited from partner, not auto-equippable at hatch.","OK"],
  ["LE_0144","MON_025|SK_FIGHTING_04","MON_025","SP_ROCK_BEAST",2,"SK_FIGHTING_04","FIGHTING","RareManual",30,2,"FIGHTING",60,"MANUAL_SK_FIGHTING_04",false,true,true,"Deferred",40,"Level >= 30 AND Bond >= 60 AND SecondaryType = FIGHTING","Manual source becomes active after Item_Master Fix #12","OK"],
  ["LE_0145","MON_008|SK_GROUND_01","MON_008","SP_GROUND_SLIME",1,"SK_GROUND_01","GROUND","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Level >= 1","Core Stage1 learnset","OK"],
  ["LE_0146","MON_008|SK_GROUND_02","MON_008","SP_GROUND_SLIME",1,"SK_GROUND_02","GROUND","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Level >= 5","Core Stage1 learnset","OK"],
  ["LE_0147","MON_008|SK_GROUND_03","MON_008","SP_GROUND_SLIME",1,"SK_GROUND_03","GROUND","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Level >= 8","Core Stage1 learnset","OK"],
  ["LE_0148","MON_008|SK_GROUND_04","MON_008","SP_GROUND_SLIME",1,"SK_GROUND_04","GROUND","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Level >= 10","Core Stage1 learnset","OK"],
  ["LE_0149","MON_008|SK_GROUND_05","MON_008","SP_GROUND_SLIME",1,"SK_GROUND_05","GROUND","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Level >= 14","Core Stage1 learnset","OK"],
  ["LE_0150","MON_026|SK_GROUND_01","MON_026","SP_GROUND_BEAST",2,"SK_GROUND_01","GROUND","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Historical level >= 1; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0151","MON_026|SK_GROUND_02","MON_026","SP_GROUND_BEAST",2,"SK_GROUND_02","GROUND","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Historical level >= 5; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0152","MON_026|SK_GROUND_03","MON_026","SP_GROUND_BEAST",2,"SK_GROUND_03","GROUND","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Historical level >= 8; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0153","MON_026|SK_GROUND_04","MON_026","SP_GROUND_BEAST",2,"SK_GROUND_04","GROUND","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Historical level >= 10; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0154","MON_026|SK_GROUND_05","MON_026","SP_GROUND_BEAST",2,"SK_GROUND_05","GROUND","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Historical level >= 14; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0155","MON_026|SK_GROUND_06","MON_026","SP_GROUND_BEAST",2,"SK_GROUND_06","GROUND","Evolution",15,2,null,0,"EVO_MON_026",true,true,true,"Active",98,"Evolution into this Stage2 form OR captured Stage2 move generation","Signature high-impact move; limited Uses","OK"],
  ["LE_0156","MON_026|SK_ROCK_01","MON_026","SP_GROUND_BEAST",2,"SK_ROCK_01","ROCK","SecondaryLevel",18,2,"ROCK",0,null,true,true,true,"Active",82,"Level >= 18 AND SecondaryType = ROCK","Secondary-type basic/offensive technique","OK"],
  ["LE_0157","MON_026|SK_ROCK_03","MON_026","SP_GROUND_BEAST",2,"SK_ROCK_03","ROCK","SecondaryLevel",30,2,"ROCK",0,null,true,true,true,"Active",76,"Level >= 30 AND SecondaryType = ROCK","Secondary-type utility/defensive technique","OK"],
  ["LE_0158","MON_026|SK_POISON_01","MON_026","SP_GROUND_BEAST",2,"SK_POISON_01","POISON","SecondaryLevel",20,2,"POISON",0,null,true,true,true,"Active",82,"Level >= 20 AND SecondaryType = POISON","Secondary-type basic/offensive technique","OK"],
  ["LE_0159","MON_026|SK_POISON_03","MON_026","SP_GROUND_BEAST",2,"SK_POISON_03","POISON","SecondaryLevel",32,2,"POISON",0,null,true,true,true,"Active",76,"Level >= 32 AND SecondaryType = POISON","Secondary-type utility/defensive technique","OK"],
  ["LE_0160","MON_026|SK_STEEL_01","MON_026","SP_GROUND_BEAST",2,"SK_STEEL_01","STEEL","SecondaryLevel",22,2,"STEEL",0,null,true,true,true,"Active",82,"Level >= 22 AND SecondaryType = STEEL","Secondary-type basic/offensive technique","OK"],
  ["LE_0161","MON_026|SK_STEEL_03","MON_026","SP_GROUND_BEAST",2,"SK_STEEL_03","STEEL","SecondaryLevel",34,2,"STEEL",0,null,true,true,true,"Active",76,"Level >= 34 AND SecondaryType = STEEL","Secondary-type utility/defensive technique","OK"],
  ["LE_0162","MON_026|SK_FIGHTING_05","MON_026","SP_GROUND_BEAST",2,"SK_FIGHTING_05","FIGHTING","Tutor",20,2,null,40,"TUTOR_BRUISER_1",false,true,true,"Active",69,"Level >= 20 AND Bond >= 40","Role tutor for Bruiser build","OK"],
  ["LE_0163","MON_026|SK_NORMAL_05","MON_026","SP_GROUND_BEAST",2,"SK_NORMAL_05","NORMAL","Tutor",28,2,null,60,"TUTOR_BRUISER_2",false,true,true,"Active",68,"Level >= 28 AND Bond >= 60","Role tutor for Bruiser build","OK"],
  ["LE_0164","MON_026|SK_POISON_02","MON_026","SP_GROUND_BEAST",2,"SK_POISON_02","POISON","BreedingCandidate",1,2,"POISON",0,"BREED_SP_GROUND_BEAST",false,true,true,"DataReady",50,"Egg inheritance candidate; target SecondaryType must allow POISON","BRD_v1.0 Skill Memory candidate; inherited from partner, not auto-equippable at hatch.","OK"],
  ["LE_0165","MON_026|SK_STEEL_04","MON_026","SP_GROUND_BEAST",2,"SK_STEEL_04","STEEL","RareManual",30,2,"STEEL",60,"MANUAL_SK_STEEL_04",false,true,true,"Deferred",40,"Level >= 30 AND Bond >= 60 AND SecondaryType = STEEL","Manual source becomes active after Item_Master Fix #12","OK"],
  ["LE_0166","MON_009|SK_FLYING_01","MON_009","SP_FLYING_SLIME",1,"SK_FLYING_01","FLYING","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Level >= 1","Core Stage1 learnset","OK"],
  ["LE_0167","MON_009|SK_FLYING_02","MON_009","SP_FLYING_SLIME",1,"SK_FLYING_02","FLYING","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Level >= 5","Core Stage1 learnset","OK"],
  ["LE_0168","MON_009|SK_FLYING_03","MON_009","SP_FLYING_SLIME",1,"SK_FLYING_03","FLYING","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Level >= 8","Core Stage1 learnset","OK"],
  ["LE_0169","MON_009|SK_FLYING_04","MON_009","SP_FLYING_SLIME",1,"SK_FLYING_04","FLYING","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Level >= 10","Core Stage1 learnset","OK"],
  ["LE_0170","MON_009|SK_FLYING_05","MON_009","SP_FLYING_SLIME",1,"SK_FLYING_05","FLYING","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Level >= 14","Core Stage1 learnset","OK"],
  ["LE_0171","MON_027|SK_FLYING_01","MON_027","SP_FLYING_BEAST",2,"SK_FLYING_01","FLYING","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Historical level >= 1; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0172","MON_027|SK_FLYING_02","MON_027","SP_FLYING_BEAST",2,"SK_FLYING_02","FLYING","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Historical level >= 5; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0173","MON_027|SK_FLYING_03","MON_027","SP_FLYING_BEAST",2,"SK_FLYING_03","FLYING","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Historical level >= 8; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0174","MON_027|SK_FLYING_04","MON_027","SP_FLYING_BEAST",2,"SK_FLYING_04","FLYING","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Historical level >= 10; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0175","MON_027|SK_FLYING_05","MON_027","SP_FLYING_BEAST",2,"SK_FLYING_05","FLYING","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Historical level >= 14; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0176","MON_027|SK_FLYING_06","MON_027","SP_FLYING_BEAST",2,"SK_FLYING_06","FLYING","Evolution",15,2,null,0,"EVO_MON_027",true,true,true,"Active",98,"Evolution into this Stage2 form OR captured Stage2 move generation","Signature high-impact move; limited Uses","OK"],
  ["LE_0177","MON_027|SK_ELECTRIC_01","MON_027","SP_FLYING_BEAST",2,"SK_ELECTRIC_01","ELECTRIC","SecondaryLevel",18,2,"ELECTRIC",0,null,true,true,true,"Active",82,"Level >= 18 AND SecondaryType = ELECTRIC","Secondary-type basic/offensive technique","OK"],
  ["LE_0178","MON_027|SK_ELECTRIC_03","MON_027","SP_FLYING_BEAST",2,"SK_ELECTRIC_03","ELECTRIC","SecondaryLevel",30,2,"ELECTRIC",0,null,true,true,true,"Active",76,"Level >= 30 AND SecondaryType = ELECTRIC","Secondary-type utility/defensive technique","OK"],
  ["LE_0179","MON_027|SK_DRAGON_01","MON_027","SP_FLYING_BEAST",2,"SK_DRAGON_01","DRAGON","SecondaryLevel",20,2,"DRAGON",0,null,true,true,true,"Active",82,"Level >= 20 AND SecondaryType = DRAGON","Secondary-type basic/offensive technique","OK"],
  ["LE_0180","MON_027|SK_DRAGON_03","MON_027","SP_FLYING_BEAST",2,"SK_DRAGON_03","DRAGON","SecondaryLevel",32,2,"DRAGON",0,null,true,true,true,"Active",76,"Level >= 32 AND SecondaryType = DRAGON","Secondary-type utility/defensive technique","OK"],
  ["LE_0181","MON_027|SK_NORMAL_01","MON_027","SP_FLYING_BEAST",2,"SK_NORMAL_01","NORMAL","SecondaryLevel",22,2,"NORMAL",0,null,true,true,true,"Active",82,"Level >= 22 AND SecondaryType = NORMAL","Secondary-type basic/offensive technique","OK"],
  ["LE_0182","MON_027|SK_NORMAL_03","MON_027","SP_FLYING_BEAST",2,"SK_NORMAL_03","NORMAL","SecondaryLevel",34,2,"NORMAL",0,null,true,true,true,"Active",76,"Level >= 34 AND SecondaryType = NORMAL","Secondary-type utility/defensive technique","OK"],
  ["LE_0183","MON_027|SK_ELECTRIC_02","MON_027","SP_FLYING_BEAST",2,"SK_ELECTRIC_02","ELECTRIC","Tutor",20,2,null,40,"TUTOR_MOBILITY_1",false,true,true,"Active",69,"Level >= 20 AND Bond >= 40","Role tutor for Mobility build","OK"],
  ["LE_0184","MON_027|SK_GHOST_02","MON_027","SP_FLYING_BEAST",2,"SK_GHOST_02","GHOST","Tutor",28,2,null,60,"TUTOR_MOBILITY_2",false,true,true,"Active",68,"Level >= 28 AND Bond >= 60","Role tutor for Mobility build","OK"],
  ["LE_0185","MON_027|SK_DRAGON_02","MON_027","SP_FLYING_BEAST",2,"SK_DRAGON_02","DRAGON","BreedingCandidate",1,2,"DRAGON",0,"BREED_SP_FLYING_BEAST",false,true,true,"DataReady",50,"Egg inheritance candidate; target SecondaryType must allow DRAGON","BRD_v1.0 Skill Memory candidate; inherited from partner, not auto-equippable at hatch.","OK"],
  ["LE_0186","MON_027|SK_NORMAL_04","MON_027","SP_FLYING_BEAST",2,"SK_NORMAL_04","NORMAL","RareManual",30,2,"NORMAL",60,"MANUAL_SK_NORMAL_04",false,true,true,"Deferred",40,"Level >= 30 AND Bond >= 60 AND SecondaryType = NORMAL","Manual source becomes active after Item_Master Fix #12","OK"],
  ["LE_0187","MON_010|SK_POISON_01","MON_010","SP_POISON_SLIME",1,"SK_POISON_01","POISON","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Level >= 1","Core Stage1 learnset","OK"],
  ["LE_0188","MON_010|SK_POISON_02","MON_010","SP_POISON_SLIME",1,"SK_POISON_02","POISON","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Level >= 5","Core Stage1 learnset","OK"],
  ["LE_0189","MON_010|SK_POISON_03","MON_010","SP_POISON_SLIME",1,"SK_POISON_03","POISON","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Level >= 8","Core Stage1 learnset","OK"],
  ["LE_0190","MON_010|SK_POISON_04","MON_010","SP_POISON_SLIME",1,"SK_POISON_04","POISON","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Level >= 10","Core Stage1 learnset","OK"],
  ["LE_0191","MON_010|SK_POISON_05","MON_010","SP_POISON_SLIME",1,"SK_POISON_05","POISON","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Level >= 14","Core Stage1 learnset","OK"],
  ["LE_0192","MON_028|SK_POISON_01","MON_028","SP_POISON_BEAST",2,"SK_POISON_01","POISON","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Historical level >= 1; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0193","MON_028|SK_POISON_02","MON_028","SP_POISON_BEAST",2,"SK_POISON_02","POISON","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Historical level >= 5; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0194","MON_028|SK_POISON_03","MON_028","SP_POISON_BEAST",2,"SK_POISON_03","POISON","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Historical level >= 8; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0195","MON_028|SK_POISON_04","MON_028","SP_POISON_BEAST",2,"SK_POISON_04","POISON","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Historical level >= 10; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0196","MON_028|SK_POISON_05","MON_028","SP_POISON_BEAST",2,"SK_POISON_05","POISON","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Historical level >= 14; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0197","MON_028|SK_POISON_06","MON_028","SP_POISON_BEAST",2,"SK_POISON_06","POISON","Evolution",15,2,null,0,"EVO_MON_028",true,true,true,"Active",98,"Evolution into this Stage2 form OR captured Stage2 move generation","Signature high-impact move; limited Uses","OK"],
  ["LE_0198","MON_028|SK_DARK_01","MON_028","SP_POISON_BEAST",2,"SK_DARK_01","DARK","SecondaryLevel",18,2,"DARK",0,null,true,true,true,"Active",82,"Level >= 18 AND SecondaryType = DARK","Secondary-type basic/offensive technique","OK"],
  ["LE_0199","MON_028|SK_DARK_03","MON_028","SP_POISON_BEAST",2,"SK_DARK_03","DARK","SecondaryLevel",30,2,"DARK",0,null,true,true,true,"Active",76,"Level >= 30 AND SecondaryType = DARK","Secondary-type utility/defensive technique","OK"],
  ["LE_0200","MON_028|SK_BUG_01","MON_028","SP_POISON_BEAST",2,"SK_BUG_01","BUG","SecondaryLevel",20,2,"BUG",0,null,true,true,true,"Active",82,"Level >= 20 AND SecondaryType = BUG","Secondary-type basic/offensive technique","OK"],
  ["LE_0201","MON_028|SK_BUG_03","MON_028","SP_POISON_BEAST",2,"SK_BUG_03","BUG","SecondaryLevel",32,2,"BUG",0,null,true,true,true,"Active",76,"Level >= 32 AND SecondaryType = BUG","Secondary-type utility/defensive technique","OK"],
  ["LE_0202","MON_028|SK_GHOST_01","MON_028","SP_POISON_BEAST",2,"SK_GHOST_01","GHOST","SecondaryLevel",22,2,"GHOST",0,null,true,true,true,"Active",82,"Level >= 22 AND SecondaryType = GHOST","Secondary-type basic/offensive technique","OK"],
  ["LE_0203","MON_028|SK_GHOST_03","MON_028","SP_POISON_BEAST",2,"SK_GHOST_03","GHOST","SecondaryLevel",34,2,"GHOST",0,null,true,true,true,"Active",76,"Level >= 34 AND SecondaryType = GHOST","Secondary-type utility/defensive technique","OK"],
  ["LE_0204","MON_028|SK_DARK_05","MON_028","SP_POISON_BEAST",2,"SK_DARK_05","DARK","Tutor",20,2,null,40,"TUTOR_DOT_1",false,true,true,"Active",69,"Level >= 20 AND Bond >= 40","Role tutor for DoT build","OK"],
  ["LE_0205","MON_028|SK_BUG_05","MON_028","SP_POISON_BEAST",2,"SK_BUG_05","BUG","Tutor",28,2,null,60,"TUTOR_DOT_2",false,true,true,"Active",68,"Level >= 28 AND Bond >= 60","Role tutor for DoT build","OK"],
  ["LE_0206","MON_028|SK_BUG_02","MON_028","SP_POISON_BEAST",2,"SK_BUG_02","BUG","BreedingCandidate",1,2,"BUG",0,"BREED_SP_POISON_BEAST",false,true,true,"DataReady",50,"Egg inheritance candidate; target SecondaryType must allow BUG","BRD_v1.0 Skill Memory candidate; inherited from partner, not auto-equippable at hatch.","OK"],
  ["LE_0207","MON_028|SK_GHOST_04","MON_028","SP_POISON_BEAST",2,"SK_GHOST_04","GHOST","RareManual",30,2,"GHOST",60,"MANUAL_SK_GHOST_04",false,true,true,"Deferred",40,"Level >= 30 AND Bond >= 60 AND SecondaryType = GHOST","Manual source becomes active after Item_Master Fix #12","OK"],
  ["LE_0208","MON_011|SK_DARK_01","MON_011","SP_DARK_SLIME",1,"SK_DARK_01","DARK","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Level >= 1","Core Stage1 learnset","OK"],
  ["LE_0209","MON_011|SK_DARK_02","MON_011","SP_DARK_SLIME",1,"SK_DARK_02","DARK","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Level >= 5","Core Stage1 learnset","OK"],
  ["LE_0210","MON_011|SK_DARK_03","MON_011","SP_DARK_SLIME",1,"SK_DARK_03","DARK","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Level >= 8","Core Stage1 learnset","OK"],
  ["LE_0211","MON_011|SK_DARK_04","MON_011","SP_DARK_SLIME",1,"SK_DARK_04","DARK","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Level >= 10","Core Stage1 learnset","OK"],
  ["LE_0212","MON_011|SK_DARK_05","MON_011","SP_DARK_SLIME",1,"SK_DARK_05","DARK","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Level >= 14","Core Stage1 learnset","OK"],
  ["LE_0213","MON_029|SK_DARK_01","MON_029","SP_DARK_BEAST",2,"SK_DARK_01","DARK","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Historical level >= 1; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0214","MON_029|SK_DARK_02","MON_029","SP_DARK_BEAST",2,"SK_DARK_02","DARK","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Historical level >= 5; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0215","MON_029|SK_DARK_03","MON_029","SP_DARK_BEAST",2,"SK_DARK_03","DARK","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Historical level >= 8; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0216","MON_029|SK_DARK_04","MON_029","SP_DARK_BEAST",2,"SK_DARK_04","DARK","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Historical level >= 10; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0217","MON_029|SK_DARK_05","MON_029","SP_DARK_BEAST",2,"SK_DARK_05","DARK","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Historical level >= 14; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0218","MON_029|SK_DARK_06","MON_029","SP_DARK_BEAST",2,"SK_DARK_06","DARK","Evolution",15,2,null,0,"EVO_MON_029",true,true,true,"Active",98,"Evolution into this Stage2 form OR captured Stage2 move generation","Signature high-impact move; limited Uses","OK"],
  ["LE_0219","MON_029|SK_GHOST_01","MON_029","SP_DARK_BEAST",2,"SK_GHOST_01","GHOST","SecondaryLevel",18,2,"GHOST",0,null,true,true,true,"Active",82,"Level >= 18 AND SecondaryType = GHOST","Secondary-type basic/offensive technique","OK"],
  ["LE_0220","MON_029|SK_GHOST_03","MON_029","SP_DARK_BEAST",2,"SK_GHOST_03","GHOST","SecondaryLevel",30,2,"GHOST",0,null,true,true,true,"Active",76,"Level >= 30 AND SecondaryType = GHOST","Secondary-type utility/defensive technique","OK"],
  ["LE_0221","MON_029|SK_POISON_01","MON_029","SP_DARK_BEAST",2,"SK_POISON_01","POISON","SecondaryLevel",20,2,"POISON",0,null,true,true,true,"Active",82,"Level >= 20 AND SecondaryType = POISON","Secondary-type basic/offensive technique","OK"],
  ["LE_0222","MON_029|SK_POISON_03","MON_029","SP_DARK_BEAST",2,"SK_POISON_03","POISON","SecondaryLevel",32,2,"POISON",0,null,true,true,true,"Active",76,"Level >= 32 AND SecondaryType = POISON","Secondary-type utility/defensive technique","OK"],
  ["LE_0223","MON_029|SK_FIRE_01","MON_029","SP_DARK_BEAST",2,"SK_FIRE_01","FIRE","SecondaryLevel",22,2,"FIRE",0,null,true,true,true,"Active",82,"Level >= 22 AND SecondaryType = FIRE","Secondary-type basic/offensive technique","OK"],
  ["LE_0224","MON_029|SK_FIRE_03","MON_029","SP_DARK_BEAST",2,"SK_FIRE_03","FIRE","SecondaryLevel",34,2,"FIRE",0,null,true,true,true,"Active",76,"Level >= 34 AND SecondaryType = FIRE","Secondary-type utility/defensive technique","OK"],
  ["LE_0225","MON_029|SK_NORMAL_05","MON_029","SP_DARK_BEAST",2,"SK_NORMAL_05","NORMAL","Tutor",20,2,null,40,"TUTOR_ASSASSIN_1",false,true,true,"Active",69,"Level >= 20 AND Bond >= 40","Role tutor for Assassin build","OK"],
  ["LE_0226","MON_029|SK_GHOST_02","MON_029","SP_DARK_BEAST",2,"SK_GHOST_02","GHOST","Tutor",28,2,null,60,"TUTOR_ASSASSIN_2",false,true,true,"Active",68,"Level >= 28 AND Bond >= 60","Role tutor for Assassin build","OK"],
  ["LE_0227","MON_029|SK_POISON_02","MON_029","SP_DARK_BEAST",2,"SK_POISON_02","POISON","BreedingCandidate",1,2,"POISON",0,"BREED_SP_DARK_BEAST",false,true,true,"DataReady",50,"Egg inheritance candidate; target SecondaryType must allow POISON","BRD_v1.0 Skill Memory candidate; inherited from partner, not auto-equippable at hatch.","OK"],
  ["LE_0228","MON_029|SK_FIRE_04","MON_029","SP_DARK_BEAST",2,"SK_FIRE_04","FIRE","RareManual",30,2,"FIRE",60,"MANUAL_SK_FIRE_04",false,true,true,"Deferred",40,"Level >= 30 AND Bond >= 60 AND SecondaryType = FIRE","Manual source becomes active after Item_Master Fix #12","OK"],
  ["LE_0229","MON_012|SK_LIGHT_01","MON_012","SP_LIGHT_SLIME",1,"SK_LIGHT_01","LIGHT","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Level >= 1","Core Stage1 learnset","OK"],
  ["LE_0230","MON_012|SK_LIGHT_02","MON_012","SP_LIGHT_SLIME",1,"SK_LIGHT_02","LIGHT","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Level >= 5","Core Stage1 learnset","OK"],
  ["LE_0231","MON_012|SK_LIGHT_03","MON_012","SP_LIGHT_SLIME",1,"SK_LIGHT_03","LIGHT","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Level >= 8","Core Stage1 learnset","OK"],
  ["LE_0232","MON_012|SK_LIGHT_04","MON_012","SP_LIGHT_SLIME",1,"SK_LIGHT_04","LIGHT","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Level >= 10","Core Stage1 learnset","OK"],
  ["LE_0233","MON_012|SK_LIGHT_05","MON_012","SP_LIGHT_SLIME",1,"SK_LIGHT_05","LIGHT","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Level >= 14","Core Stage1 learnset","OK"],
  ["LE_0234","MON_030|SK_LIGHT_01","MON_030","SP_LIGHT_BEAST",2,"SK_LIGHT_01","LIGHT","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Historical level >= 1; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0235","MON_030|SK_LIGHT_02","MON_030","SP_LIGHT_BEAST",2,"SK_LIGHT_02","LIGHT","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Historical level >= 5; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0236","MON_030|SK_LIGHT_03","MON_030","SP_LIGHT_BEAST",2,"SK_LIGHT_03","LIGHT","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Historical level >= 8; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0237","MON_030|SK_LIGHT_04","MON_030","SP_LIGHT_BEAST",2,"SK_LIGHT_04","LIGHT","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Historical level >= 10; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0238","MON_030|SK_LIGHT_05","MON_030","SP_LIGHT_BEAST",2,"SK_LIGHT_05","LIGHT","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Historical level >= 14; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0239","MON_030|SK_LIGHT_06","MON_030","SP_LIGHT_BEAST",2,"SK_LIGHT_06","LIGHT","Evolution",15,2,null,0,"EVO_MON_030",true,true,true,"Active",98,"Evolution into this Stage2 form OR captured Stage2 move generation","Signature high-impact move; limited Uses","OK"],
  ["LE_0240","MON_030|SK_PSYCHIC_01","MON_030","SP_LIGHT_BEAST",2,"SK_PSYCHIC_01","PSYCHIC","SecondaryLevel",18,2,"PSYCHIC",0,null,true,true,true,"Active",82,"Level >= 18 AND SecondaryType = PSYCHIC","Secondary-type basic/offensive technique","OK"],
  ["LE_0241","MON_030|SK_PSYCHIC_03","MON_030","SP_LIGHT_BEAST",2,"SK_PSYCHIC_03","PSYCHIC","SecondaryLevel",30,2,"PSYCHIC",0,null,true,true,true,"Active",76,"Level >= 30 AND SecondaryType = PSYCHIC","Secondary-type utility/defensive technique","OK"],
  ["LE_0242","MON_030|SK_FLYING_01","MON_030","SP_LIGHT_BEAST",2,"SK_FLYING_01","FLYING","SecondaryLevel",20,2,"FLYING",0,null,true,true,true,"Active",82,"Level >= 20 AND SecondaryType = FLYING","Secondary-type basic/offensive technique","OK"],
  ["LE_0243","MON_030|SK_FLYING_03","MON_030","SP_LIGHT_BEAST",2,"SK_FLYING_03","FLYING","SecondaryLevel",32,2,"FLYING",0,null,true,true,true,"Active",76,"Level >= 32 AND SecondaryType = FLYING","Secondary-type utility/defensive technique","OK"],
  ["LE_0244","MON_030|SK_STEEL_01","MON_030","SP_LIGHT_BEAST",2,"SK_STEEL_01","STEEL","SecondaryLevel",22,2,"STEEL",0,null,true,true,true,"Active",82,"Level >= 22 AND SecondaryType = STEEL","Secondary-type basic/offensive technique","OK"],
  ["LE_0245","MON_030|SK_STEEL_03","MON_030","SP_LIGHT_BEAST",2,"SK_STEEL_03","STEEL","SecondaryLevel",34,2,"STEEL",0,null,true,true,true,"Active",76,"Level >= 34 AND SecondaryType = STEEL","Secondary-type utility/defensive technique","OK"],
  ["LE_0246","MON_030|SK_FLYING_02","MON_030","SP_LIGHT_BEAST",2,"SK_FLYING_02","FLYING","BreedingCandidate",1,2,"FLYING",0,"BREED_SP_LIGHT_BEAST",false,true,true,"DataReady",50,"Egg inheritance candidate; target SecondaryType must allow FLYING","BRD_v1.0 Skill Memory candidate; inherited from partner, not auto-equippable at hatch.","OK"],
  ["LE_0247","MON_030|SK_STEEL_04","MON_030","SP_LIGHT_BEAST",2,"SK_STEEL_04","STEEL","RareManual",30,2,"STEEL",60,"MANUAL_SK_STEEL_04",false,true,true,"Deferred",40,"Level >= 30 AND Bond >= 60 AND SecondaryType = STEEL","Manual source becomes active after Item_Master Fix #12","OK"],
  ["LE_0248","MON_013|SK_PSYCHIC_01","MON_013","SP_PSYCHIC_SLIME",1,"SK_PSYCHIC_01","PSYCHIC","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Level >= 1","Core Stage1 learnset","OK"],
  ["LE_0249","MON_013|SK_PSYCHIC_02","MON_013","SP_PSYCHIC_SLIME",1,"SK_PSYCHIC_02","PSYCHIC","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Level >= 5","Core Stage1 learnset","OK"],
  ["LE_0250","MON_013|SK_PSYCHIC_03","MON_013","SP_PSYCHIC_SLIME",1,"SK_PSYCHIC_03","PSYCHIC","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Level >= 8","Core Stage1 learnset","OK"],
  ["LE_0251","MON_013|SK_PSYCHIC_04","MON_013","SP_PSYCHIC_SLIME",1,"SK_PSYCHIC_04","PSYCHIC","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Level >= 10","Core Stage1 learnset","OK"],
  ["LE_0252","MON_013|SK_PSYCHIC_05","MON_013","SP_PSYCHIC_SLIME",1,"SK_PSYCHIC_05","PSYCHIC","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Level >= 14","Core Stage1 learnset","OK"],
  ["LE_0253","MON_031|SK_PSYCHIC_01","MON_031","SP_PSYCHIC_BEAST",2,"SK_PSYCHIC_01","PSYCHIC","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Historical level >= 1; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0254","MON_031|SK_PSYCHIC_02","MON_031","SP_PSYCHIC_BEAST",2,"SK_PSYCHIC_02","PSYCHIC","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Historical level >= 5; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0255","MON_031|SK_PSYCHIC_03","MON_031","SP_PSYCHIC_BEAST",2,"SK_PSYCHIC_03","PSYCHIC","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Historical level >= 8; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0256","MON_031|SK_PSYCHIC_04","MON_031","SP_PSYCHIC_BEAST",2,"SK_PSYCHIC_04","PSYCHIC","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Historical level >= 10; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0257","MON_031|SK_PSYCHIC_05","MON_031","SP_PSYCHIC_BEAST",2,"SK_PSYCHIC_05","PSYCHIC","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Historical level >= 14; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0258","MON_031|SK_PSYCHIC_06","MON_031","SP_PSYCHIC_BEAST",2,"SK_PSYCHIC_06","PSYCHIC","Evolution",15,2,null,0,"EVO_MON_031",true,true,true,"Active",98,"Evolution into this Stage2 form OR captured Stage2 move generation","Signature high-impact move; limited Uses","OK"],
  ["LE_0259","MON_031|SK_LIGHT_01","MON_031","SP_PSYCHIC_BEAST",2,"SK_LIGHT_01","LIGHT","SecondaryLevel",18,2,"LIGHT",0,null,true,true,true,"Active",82,"Level >= 18 AND SecondaryType = LIGHT","Secondary-type basic/offensive technique","OK"],
  ["LE_0260","MON_031|SK_LIGHT_03","MON_031","SP_PSYCHIC_BEAST",2,"SK_LIGHT_03","LIGHT","SecondaryLevel",30,2,"LIGHT",0,null,true,true,true,"Active",76,"Level >= 30 AND SecondaryType = LIGHT","Secondary-type utility/defensive technique","OK"],
  ["LE_0261","MON_031|SK_GHOST_01","MON_031","SP_PSYCHIC_BEAST",2,"SK_GHOST_01","GHOST","SecondaryLevel",20,2,"GHOST",0,null,true,true,true,"Active",82,"Level >= 20 AND SecondaryType = GHOST","Secondary-type basic/offensive technique","OK"],
  ["LE_0262","MON_031|SK_GHOST_03","MON_031","SP_PSYCHIC_BEAST",2,"SK_GHOST_03","GHOST","SecondaryLevel",32,2,"GHOST",0,null,true,true,true,"Active",76,"Level >= 32 AND SecondaryType = GHOST","Secondary-type utility/defensive technique","OK"],
  ["LE_0263","MON_031|SK_DARK_01","MON_031","SP_PSYCHIC_BEAST",2,"SK_DARK_01","DARK","SecondaryLevel",22,2,"DARK",0,null,true,true,true,"Active",82,"Level >= 22 AND SecondaryType = DARK","Secondary-type basic/offensive technique","OK"],
  ["LE_0264","MON_031|SK_DARK_03","MON_031","SP_PSYCHIC_BEAST",2,"SK_DARK_03","DARK","SecondaryLevel",34,2,"DARK",0,null,true,true,true,"Active",76,"Level >= 34 AND SecondaryType = DARK","Secondary-type utility/defensive technique","OK"],
  ["LE_0265","MON_031|SK_NORMAL_05","MON_031","SP_PSYCHIC_BEAST",2,"SK_NORMAL_05","NORMAL","Tutor",20,2,null,40,"TUTOR_CONTROL_1",false,true,true,"Active",69,"Level >= 20 AND Bond >= 40","Role tutor for Control build","OK"],
  ["LE_0266","MON_031|SK_BUG_04","MON_031","SP_PSYCHIC_BEAST",2,"SK_BUG_04","BUG","Tutor",28,2,null,60,"TUTOR_CONTROL_2",false,true,true,"Active",68,"Level >= 28 AND Bond >= 60","Role tutor for Control build","OK"],
  ["LE_0267","MON_031|SK_GHOST_02","MON_031","SP_PSYCHIC_BEAST",2,"SK_GHOST_02","GHOST","BreedingCandidate",1,2,"GHOST",0,"BREED_SP_PSYCHIC_BEAST",false,true,true,"DataReady",50,"Egg inheritance candidate; target SecondaryType must allow GHOST","BRD_v1.0 Skill Memory candidate; inherited from partner, not auto-equippable at hatch.","OK"],
  ["LE_0268","MON_031|SK_DARK_04","MON_031","SP_PSYCHIC_BEAST",2,"SK_DARK_04","DARK","RareManual",30,2,"DARK",60,"MANUAL_SK_DARK_04",false,true,true,"Deferred",40,"Level >= 30 AND Bond >= 60 AND SecondaryType = DARK","Manual source becomes active after Item_Master Fix #12","OK"],
  ["LE_0269","MON_014|SK_BUG_01","MON_014","SP_BUG_SLIME",1,"SK_BUG_01","BUG","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Level >= 1","Core Stage1 learnset","OK"],
  ["LE_0270","MON_014|SK_BUG_02","MON_014","SP_BUG_SLIME",1,"SK_BUG_02","BUG","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Level >= 5","Core Stage1 learnset","OK"],
  ["LE_0271","MON_014|SK_BUG_03","MON_014","SP_BUG_SLIME",1,"SK_BUG_03","BUG","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Level >= 8","Core Stage1 learnset","OK"],
  ["LE_0272","MON_014|SK_BUG_04","MON_014","SP_BUG_SLIME",1,"SK_BUG_04","BUG","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Level >= 10","Core Stage1 learnset","OK"],
  ["LE_0273","MON_014|SK_BUG_05","MON_014","SP_BUG_SLIME",1,"SK_BUG_05","BUG","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Level >= 14","Core Stage1 learnset","OK"],
  ["LE_0274","MON_032|SK_BUG_01","MON_032","SP_BUG_BEAST",2,"SK_BUG_01","BUG","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Historical level >= 1; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0275","MON_032|SK_BUG_02","MON_032","SP_BUG_BEAST",2,"SK_BUG_02","BUG","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Historical level >= 5; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0276","MON_032|SK_BUG_03","MON_032","SP_BUG_BEAST",2,"SK_BUG_03","BUG","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Historical level >= 8; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0277","MON_032|SK_BUG_04","MON_032","SP_BUG_BEAST",2,"SK_BUG_04","BUG","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Historical level >= 10; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0278","MON_032|SK_BUG_05","MON_032","SP_BUG_BEAST",2,"SK_BUG_05","BUG","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Historical level >= 14; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0279","MON_032|SK_BUG_06","MON_032","SP_BUG_BEAST",2,"SK_BUG_06","BUG","Evolution",15,2,null,0,"EVO_MON_032",true,true,true,"Active",98,"Evolution into this Stage2 form OR captured Stage2 move generation","Signature high-impact move; limited Uses","OK"],
  ["LE_0280","MON_032|SK_GRASS_01","MON_032","SP_BUG_BEAST",2,"SK_GRASS_01","GRASS","SecondaryLevel",18,2,"GRASS",0,null,true,true,true,"Active",82,"Level >= 18 AND SecondaryType = GRASS","Secondary-type basic/offensive technique","OK"],
  ["LE_0281","MON_032|SK_GRASS_03","MON_032","SP_BUG_BEAST",2,"SK_GRASS_03","GRASS","SecondaryLevel",30,2,"GRASS",0,null,true,true,true,"Active",76,"Level >= 30 AND SecondaryType = GRASS","Secondary-type utility/defensive technique","OK"],
  ["LE_0282","MON_032|SK_POISON_01","MON_032","SP_BUG_BEAST",2,"SK_POISON_01","POISON","SecondaryLevel",20,2,"POISON",0,null,true,true,true,"Active",82,"Level >= 20 AND SecondaryType = POISON","Secondary-type basic/offensive technique","OK"],
  ["LE_0283","MON_032|SK_POISON_03","MON_032","SP_BUG_BEAST",2,"SK_POISON_03","POISON","SecondaryLevel",32,2,"POISON",0,null,true,true,true,"Active",76,"Level >= 32 AND SecondaryType = POISON","Secondary-type utility/defensive technique","OK"],
  ["LE_0284","MON_032|SK_FLYING_01","MON_032","SP_BUG_BEAST",2,"SK_FLYING_01","FLYING","SecondaryLevel",22,2,"FLYING",0,null,true,true,true,"Active",82,"Level >= 22 AND SecondaryType = FLYING","Secondary-type basic/offensive technique","OK"],
  ["LE_0285","MON_032|SK_FLYING_03","MON_032","SP_BUG_BEAST",2,"SK_FLYING_03","FLYING","SecondaryLevel",34,2,"FLYING",0,null,true,true,true,"Active",76,"Level >= 34 AND SecondaryType = FLYING","Secondary-type utility/defensive technique","OK"],
  ["LE_0286","MON_032|SK_PSYCHIC_02","MON_032","SP_BUG_BEAST",2,"SK_PSYCHIC_02","PSYCHIC","Tutor",20,2,null,40,"TUTOR_UTILITY_1",false,true,true,"Active",69,"Level >= 20 AND Bond >= 40","Role tutor for Utility build","OK"],
  ["LE_0287","MON_032|SK_NORMAL_03","MON_032","SP_BUG_BEAST",2,"SK_NORMAL_03","NORMAL","Tutor",28,2,null,60,"TUTOR_UTILITY_2",false,true,true,"Active",68,"Level >= 28 AND Bond >= 60","Role tutor for Utility build","OK"],
  ["LE_0288","MON_032|SK_POISON_02","MON_032","SP_BUG_BEAST",2,"SK_POISON_02","POISON","BreedingCandidate",1,2,"POISON",0,"BREED_SP_BUG_BEAST",false,true,true,"DataReady",50,"Egg inheritance candidate; target SecondaryType must allow POISON","BRD_v1.0 Skill Memory candidate; inherited from partner, not auto-equippable at hatch.","OK"],
  ["LE_0289","MON_032|SK_FLYING_04","MON_032","SP_BUG_BEAST",2,"SK_FLYING_04","FLYING","RareManual",30,2,"FLYING",60,"MANUAL_SK_FLYING_04",false,true,true,"Deferred",40,"Level >= 30 AND Bond >= 60 AND SecondaryType = FLYING","Manual source becomes active after Item_Master Fix #12","OK"],
  ["LE_0290","MON_015|SK_DRAGON_01","MON_015","SP_DRAGON_SLIME",1,"SK_DRAGON_01","DRAGON","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Level >= 1","Core Stage1 learnset","OK"],
  ["LE_0291","MON_015|SK_DRAGON_02","MON_015","SP_DRAGON_SLIME",1,"SK_DRAGON_02","DRAGON","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Level >= 5","Core Stage1 learnset","OK"],
  ["LE_0292","MON_015|SK_DRAGON_03","MON_015","SP_DRAGON_SLIME",1,"SK_DRAGON_03","DRAGON","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Level >= 8","Core Stage1 learnset","OK"],
  ["LE_0293","MON_015|SK_DRAGON_04","MON_015","SP_DRAGON_SLIME",1,"SK_DRAGON_04","DRAGON","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Level >= 10","Core Stage1 learnset","OK"],
  ["LE_0294","MON_015|SK_DRAGON_05","MON_015","SP_DRAGON_SLIME",1,"SK_DRAGON_05","DRAGON","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Level >= 14","Core Stage1 learnset","OK"],
  ["LE_0295","MON_033|SK_DRAGON_01","MON_033","SP_DRAGON_BEAST",2,"SK_DRAGON_01","DRAGON","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Historical level >= 1; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0296","MON_033|SK_DRAGON_02","MON_033","SP_DRAGON_BEAST",2,"SK_DRAGON_02","DRAGON","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Historical level >= 5; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0297","MON_033|SK_DRAGON_03","MON_033","SP_DRAGON_BEAST",2,"SK_DRAGON_03","DRAGON","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Historical level >= 8; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0298","MON_033|SK_DRAGON_04","MON_033","SP_DRAGON_BEAST",2,"SK_DRAGON_04","DRAGON","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Historical level >= 10; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0299","MON_033|SK_DRAGON_05","MON_033","SP_DRAGON_BEAST",2,"SK_DRAGON_05","DRAGON","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Historical level >= 14; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0300","MON_033|SK_DRAGON_06","MON_033","SP_DRAGON_BEAST",2,"SK_DRAGON_06","DRAGON","Evolution",15,2,null,0,"EVO_MON_033",true,true,true,"Active",98,"Evolution into this Stage2 form OR captured Stage2 move generation","Signature high-impact move; limited Uses","OK"],
  ["LE_0301","MON_033|SK_FIRE_01","MON_033","SP_DRAGON_BEAST",2,"SK_FIRE_01","FIRE","SecondaryLevel",18,2,"FIRE",0,null,true,true,true,"Active",82,"Level >= 18 AND SecondaryType = FIRE","Secondary-type basic/offensive technique","OK"],
  ["LE_0302","MON_033|SK_FIRE_03","MON_033","SP_DRAGON_BEAST",2,"SK_FIRE_03","FIRE","SecondaryLevel",30,2,"FIRE",0,null,true,true,true,"Active",76,"Level >= 30 AND SecondaryType = FIRE","Secondary-type utility/defensive technique","OK"],
  ["LE_0303","MON_033|SK_ELECTRIC_01","MON_033","SP_DRAGON_BEAST",2,"SK_ELECTRIC_01","ELECTRIC","SecondaryLevel",20,2,"ELECTRIC",0,null,true,true,true,"Active",82,"Level >= 20 AND SecondaryType = ELECTRIC","Secondary-type basic/offensive technique","OK"],
  ["LE_0304","MON_033|SK_ELECTRIC_03","MON_033","SP_DRAGON_BEAST",2,"SK_ELECTRIC_03","ELECTRIC","SecondaryLevel",32,2,"ELECTRIC",0,null,true,true,true,"Active",76,"Level >= 32 AND SecondaryType = ELECTRIC","Secondary-type utility/defensive technique","OK"],
  ["LE_0305","MON_033|SK_FLYING_01","MON_033","SP_DRAGON_BEAST",2,"SK_FLYING_01","FLYING","SecondaryLevel",22,2,"FLYING",0,null,true,true,true,"Active",82,"Level >= 22 AND SecondaryType = FLYING","Secondary-type basic/offensive technique","OK"],
  ["LE_0306","MON_033|SK_FLYING_03","MON_033","SP_DRAGON_BEAST",2,"SK_FLYING_03","FLYING","SecondaryLevel",34,2,"FLYING",0,null,true,true,true,"Active",76,"Level >= 34 AND SecondaryType = FLYING","Secondary-type utility/defensive technique","OK"],
  ["LE_0307","MON_033|SK_NORMAL_05","MON_033","SP_DRAGON_BEAST",2,"SK_NORMAL_05","NORMAL","Tutor",20,2,null,40,"TUTOR_SCALER_1",false,true,true,"Active",69,"Level >= 20 AND Bond >= 40","Role tutor for Scaler build","OK"],
  ["LE_0308","MON_033|SK_LIGHT_05","MON_033","SP_DRAGON_BEAST",2,"SK_LIGHT_05","LIGHT","Tutor",28,2,null,60,"TUTOR_SCALER_2",false,true,true,"Active",68,"Level >= 28 AND Bond >= 60","Role tutor for Scaler build","OK"],
  ["LE_0309","MON_033|SK_ELECTRIC_02","MON_033","SP_DRAGON_BEAST",2,"SK_ELECTRIC_02","ELECTRIC","BreedingCandidate",1,2,"ELECTRIC",0,"BREED_SP_DRAGON_BEAST",false,true,true,"DataReady",50,"Egg inheritance candidate; target SecondaryType must allow ELECTRIC","BRD_v1.0 Skill Memory candidate; inherited from partner, not auto-equippable at hatch.","OK"],
  ["LE_0310","MON_033|SK_FLYING_04","MON_033","SP_DRAGON_BEAST",2,"SK_FLYING_04","FLYING","RareManual",30,2,"FLYING",60,"MANUAL_SK_FLYING_04",false,true,true,"Deferred",40,"Level >= 30 AND Bond >= 60 AND SecondaryType = FLYING","Manual source becomes active after Item_Master Fix #12","OK"],
  ["LE_0311","MON_016|SK_FIGHTING_01","MON_016","SP_FIGHTING_SLIME",1,"SK_FIGHTING_01","FIGHTING","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Level >= 1","Core Stage1 learnset","OK"],
  ["LE_0312","MON_016|SK_FIGHTING_02","MON_016","SP_FIGHTING_SLIME",1,"SK_FIGHTING_02","FIGHTING","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Level >= 5","Core Stage1 learnset","OK"],
  ["LE_0313","MON_016|SK_FIGHTING_03","MON_016","SP_FIGHTING_SLIME",1,"SK_FIGHTING_03","FIGHTING","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Level >= 8","Core Stage1 learnset","OK"],
  ["LE_0314","MON_016|SK_FIGHTING_04","MON_016","SP_FIGHTING_SLIME",1,"SK_FIGHTING_04","FIGHTING","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Level >= 10","Core Stage1 learnset","OK"],
  ["LE_0315","MON_016|SK_FIGHTING_05","MON_016","SP_FIGHTING_SLIME",1,"SK_FIGHTING_05","FIGHTING","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Level >= 14","Core Stage1 learnset","OK"],
  ["LE_0316","MON_034|SK_FIGHTING_01","MON_034","SP_FIGHTING_BEAST",2,"SK_FIGHTING_01","FIGHTING","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Historical level >= 1; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0317","MON_034|SK_FIGHTING_02","MON_034","SP_FIGHTING_BEAST",2,"SK_FIGHTING_02","FIGHTING","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Historical level >= 5; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0318","MON_034|SK_FIGHTING_03","MON_034","SP_FIGHTING_BEAST",2,"SK_FIGHTING_03","FIGHTING","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Historical level >= 8; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0319","MON_034|SK_FIGHTING_04","MON_034","SP_FIGHTING_BEAST",2,"SK_FIGHTING_04","FIGHTING","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Historical level >= 10; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0320","MON_034|SK_FIGHTING_05","MON_034","SP_FIGHTING_BEAST",2,"SK_FIGHTING_05","FIGHTING","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Historical level >= 14; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0321","MON_034|SK_FIGHTING_06","MON_034","SP_FIGHTING_BEAST",2,"SK_FIGHTING_06","FIGHTING","Evolution",15,2,null,0,"EVO_MON_034",true,true,true,"Active",98,"Evolution into this Stage2 form OR captured Stage2 move generation","Signature high-impact move; limited Uses","OK"],
  ["LE_0322","MON_034|SK_ROCK_01","MON_034","SP_FIGHTING_BEAST",2,"SK_ROCK_01","ROCK","SecondaryLevel",18,2,"ROCK",0,null,true,true,true,"Active",82,"Level >= 18 AND SecondaryType = ROCK","Secondary-type basic/offensive technique","OK"],
  ["LE_0323","MON_034|SK_ROCK_03","MON_034","SP_FIGHTING_BEAST",2,"SK_ROCK_03","ROCK","SecondaryLevel",30,2,"ROCK",0,null,true,true,true,"Active",76,"Level >= 30 AND SecondaryType = ROCK","Secondary-type utility/defensive technique","OK"],
  ["LE_0324","MON_034|SK_STEEL_01","MON_034","SP_FIGHTING_BEAST",2,"SK_STEEL_01","STEEL","SecondaryLevel",20,2,"STEEL",0,null,true,true,true,"Active",82,"Level >= 20 AND SecondaryType = STEEL","Secondary-type basic/offensive technique","OK"],
  ["LE_0325","MON_034|SK_STEEL_03","MON_034","SP_FIGHTING_BEAST",2,"SK_STEEL_03","STEEL","SecondaryLevel",32,2,"STEEL",0,null,true,true,true,"Active",76,"Level >= 32 AND SecondaryType = STEEL","Secondary-type utility/defensive technique","OK"],
  ["LE_0326","MON_034|SK_NORMAL_01","MON_034","SP_FIGHTING_BEAST",2,"SK_NORMAL_01","NORMAL","SecondaryLevel",22,2,"NORMAL",0,null,true,true,true,"Active",82,"Level >= 22 AND SecondaryType = NORMAL","Secondary-type basic/offensive technique","OK"],
  ["LE_0327","MON_034|SK_NORMAL_03","MON_034","SP_FIGHTING_BEAST",2,"SK_NORMAL_03","NORMAL","SecondaryLevel",34,2,"NORMAL",0,null,true,true,true,"Active",76,"Level >= 34 AND SecondaryType = NORMAL","Secondary-type utility/defensive technique","OK"],
  ["LE_0328","MON_034|SK_NORMAL_05","MON_034","SP_FIGHTING_BEAST",2,"SK_NORMAL_05","NORMAL","Tutor",20,2,null,40,"TUTOR_COMBO_1",false,true,true,"Active",69,"Level >= 20 AND Bond >= 40","Role tutor for Combo build","OK"],
  ["LE_0329","MON_034|SK_FLYING_04","MON_034","SP_FIGHTING_BEAST",2,"SK_FLYING_04","FLYING","Tutor",28,2,null,60,"TUTOR_COMBO_2",false,true,true,"Active",68,"Level >= 28 AND Bond >= 60","Role tutor for Combo build","OK"],
  ["LE_0330","MON_034|SK_STEEL_02","MON_034","SP_FIGHTING_BEAST",2,"SK_STEEL_02","STEEL","BreedingCandidate",1,2,"STEEL",0,"BREED_SP_FIGHTING_BEAST",false,true,true,"DataReady",50,"Egg inheritance candidate; target SecondaryType must allow STEEL","BRD_v1.0 Skill Memory candidate; inherited from partner, not auto-equippable at hatch.","OK"],
  ["LE_0331","MON_034|SK_NORMAL_04","MON_034","SP_FIGHTING_BEAST",2,"SK_NORMAL_04","NORMAL","RareManual",30,2,"NORMAL",60,"MANUAL_SK_NORMAL_04",false,true,true,"Deferred",40,"Level >= 30 AND Bond >= 60 AND SecondaryType = NORMAL","Manual source becomes active after Item_Master Fix #12","OK"],
  ["LE_0332","MON_017|SK_STEEL_01","MON_017","SP_STEEL_SLIME",1,"SK_STEEL_01","STEEL","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Level >= 1","Core Stage1 learnset","OK"],
  ["LE_0333","MON_017|SK_STEEL_02","MON_017","SP_STEEL_SLIME",1,"SK_STEEL_02","STEEL","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Level >= 5","Core Stage1 learnset","OK"],
  ["LE_0334","MON_017|SK_STEEL_03","MON_017","SP_STEEL_SLIME",1,"SK_STEEL_03","STEEL","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Level >= 8","Core Stage1 learnset","OK"],
  ["LE_0335","MON_017|SK_STEEL_04","MON_017","SP_STEEL_SLIME",1,"SK_STEEL_04","STEEL","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Level >= 10","Core Stage1 learnset","OK"],
  ["LE_0336","MON_017|SK_STEEL_05","MON_017","SP_STEEL_SLIME",1,"SK_STEEL_05","STEEL","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Level >= 14","Core Stage1 learnset","OK"],
  ["LE_0337","MON_035|SK_STEEL_01","MON_035","SP_STEEL_BEAST",2,"SK_STEEL_01","STEEL","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Historical level >= 1; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0338","MON_035|SK_STEEL_02","MON_035","SP_STEEL_BEAST",2,"SK_STEEL_02","STEEL","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Historical level >= 5; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0339","MON_035|SK_STEEL_03","MON_035","SP_STEEL_BEAST",2,"SK_STEEL_03","STEEL","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Historical level >= 8; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0340","MON_035|SK_STEEL_04","MON_035","SP_STEEL_BEAST",2,"SK_STEEL_04","STEEL","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Historical level >= 10; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0341","MON_035|SK_STEEL_05","MON_035","SP_STEEL_BEAST",2,"SK_STEEL_05","STEEL","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Historical level >= 14; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0342","MON_035|SK_STEEL_06","MON_035","SP_STEEL_BEAST",2,"SK_STEEL_06","STEEL","Evolution",15,2,null,0,"EVO_MON_035",true,true,true,"Active",98,"Evolution into this Stage2 form OR captured Stage2 move generation","Signature high-impact move; limited Uses","OK"],
  ["LE_0343","MON_035|SK_ROCK_01","MON_035","SP_STEEL_BEAST",2,"SK_ROCK_01","ROCK","SecondaryLevel",18,2,"ROCK",0,null,true,true,true,"Active",82,"Level >= 18 AND SecondaryType = ROCK","Secondary-type basic/offensive technique","OK"],
  ["LE_0344","MON_035|SK_ROCK_03","MON_035","SP_STEEL_BEAST",2,"SK_ROCK_03","ROCK","SecondaryLevel",30,2,"ROCK",0,null,true,true,true,"Active",76,"Level >= 30 AND SecondaryType = ROCK","Secondary-type utility/defensive technique","OK"],
  ["LE_0345","MON_035|SK_ELECTRIC_01","MON_035","SP_STEEL_BEAST",2,"SK_ELECTRIC_01","ELECTRIC","SecondaryLevel",20,2,"ELECTRIC",0,null,true,true,true,"Active",82,"Level >= 20 AND SecondaryType = ELECTRIC","Secondary-type basic/offensive technique","OK"],
  ["LE_0346","MON_035|SK_ELECTRIC_03","MON_035","SP_STEEL_BEAST",2,"SK_ELECTRIC_03","ELECTRIC","SecondaryLevel",32,2,"ELECTRIC",0,null,true,true,true,"Active",76,"Level >= 32 AND SecondaryType = ELECTRIC","Secondary-type utility/defensive technique","OK"],
  ["LE_0347","MON_035|SK_FIGHTING_01","MON_035","SP_STEEL_BEAST",2,"SK_FIGHTING_01","FIGHTING","SecondaryLevel",22,2,"FIGHTING",0,null,true,true,true,"Active",82,"Level >= 22 AND SecondaryType = FIGHTING","Secondary-type basic/offensive technique","OK"],
  ["LE_0348","MON_035|SK_FIGHTING_03","MON_035","SP_STEEL_BEAST",2,"SK_FIGHTING_03","FIGHTING","SecondaryLevel",34,2,"FIGHTING",0,null,true,true,true,"Active",76,"Level >= 34 AND SecondaryType = FIGHTING","Secondary-type utility/defensive technique","OK"],
  ["LE_0349","MON_035|SK_NORMAL_03","MON_035","SP_STEEL_BEAST",2,"SK_NORMAL_03","NORMAL","Tutor",20,2,null,40,"TUTOR_TANK_1",false,true,true,"Active",69,"Level >= 20 AND Bond >= 40","Role tutor for Tank build","OK"],
  ["LE_0350","MON_035|SK_ELECTRIC_02","MON_035","SP_STEEL_BEAST",2,"SK_ELECTRIC_02","ELECTRIC","BreedingCandidate",1,2,"ELECTRIC",0,"BREED_SP_STEEL_BEAST",false,true,true,"DataReady",50,"Egg inheritance candidate; target SecondaryType must allow ELECTRIC","BRD_v1.0 Skill Memory candidate; inherited from partner, not auto-equippable at hatch.","OK"],
  ["LE_0351","MON_035|SK_FIGHTING_04","MON_035","SP_STEEL_BEAST",2,"SK_FIGHTING_04","FIGHTING","RareManual",30,2,"FIGHTING",60,"MANUAL_SK_FIGHTING_04",false,true,true,"Deferred",40,"Level >= 30 AND Bond >= 60 AND SecondaryType = FIGHTING","Manual source becomes active after Item_Master Fix #12","OK"],
  ["LE_0352","MON_018|SK_GHOST_01","MON_018","SP_GHOST_SLIME",1,"SK_GHOST_01","GHOST","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Level >= 1","Core Stage1 learnset","OK"],
  ["LE_0353","MON_018|SK_GHOST_02","MON_018","SP_GHOST_SLIME",1,"SK_GHOST_02","GHOST","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Level >= 5","Core Stage1 learnset","OK"],
  ["LE_0354","MON_018|SK_GHOST_03","MON_018","SP_GHOST_SLIME",1,"SK_GHOST_03","GHOST","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Level >= 8","Core Stage1 learnset","OK"],
  ["LE_0355","MON_018|SK_GHOST_04","MON_018","SP_GHOST_SLIME",1,"SK_GHOST_04","GHOST","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Level >= 10","Core Stage1 learnset","OK"],
  ["LE_0356","MON_018|SK_GHOST_05","MON_018","SP_GHOST_SLIME",1,"SK_GHOST_05","GHOST","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Level >= 14","Core Stage1 learnset","OK"],
  ["LE_0357","MON_036|SK_GHOST_01","MON_036","SP_GHOST_BEAST",2,"SK_GHOST_01","GHOST","LevelUp",1,1,null,0,null,true,true,true,"Active",100,"Historical level >= 1; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0358","MON_036|SK_GHOST_02","MON_036","SP_GHOST_BEAST",2,"SK_GHOST_02","GHOST","LevelUp",5,1,null,0,null,true,true,true,"Active",95,"Historical level >= 5; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0359","MON_036|SK_GHOST_03","MON_036","SP_GHOST_BEAST",2,"SK_GHOST_03","GHOST","LevelUp",8,1,null,0,null,true,true,true,"Active",90,"Historical level >= 8; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0360","MON_036|SK_GHOST_04","MON_036","SP_GHOST_BEAST",2,"SK_GHOST_04","GHOST","LevelUp",10,1,null,0,null,true,true,true,"Active",90,"Historical level >= 10; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0361","MON_036|SK_GHOST_05","MON_036","SP_GHOST_BEAST",2,"SK_GHOST_05","GHOST","LevelUp",14,1,null,0,null,true,true,true,"Active",85,"Historical level >= 14; captured Stage2 may generate as known move","Core native move; retained from Stage1 or available through relearn","OK"],
  ["LE_0362","MON_036|SK_GHOST_06","MON_036","SP_GHOST_BEAST",2,"SK_GHOST_06","GHOST","Evolution",15,2,null,0,"EVO_MON_036",true,true,true,"Active",98,"Evolution into this Stage2 form OR captured Stage2 move generation","Signature high-impact move; limited Uses","OK"],
  ["LE_0363","MON_036|SK_DARK_01","MON_036","SP_GHOST_BEAST",2,"SK_DARK_01","DARK","SecondaryLevel",18,2,"DARK",0,null,true,true,true,"Active",82,"Level >= 18 AND SecondaryType = DARK","Secondary-type basic/offensive technique","OK"],
  ["LE_0364","MON_036|SK_DARK_03","MON_036","SP_GHOST_BEAST",2,"SK_DARK_03","DARK","SecondaryLevel",30,2,"DARK",0,null,true,true,true,"Active",76,"Level >= 30 AND SecondaryType = DARK","Secondary-type utility/defensive technique","OK"],
  ["LE_0365","MON_036|SK_PSYCHIC_01","MON_036","SP_GHOST_BEAST",2,"SK_PSYCHIC_01","PSYCHIC","SecondaryLevel",20,2,"PSYCHIC",0,null,true,true,true,"Active",82,"Level >= 20 AND SecondaryType = PSYCHIC","Secondary-type basic/offensive technique","OK"],
  ["LE_0366","MON_036|SK_PSYCHIC_03","MON_036","SP_GHOST_BEAST",2,"SK_PSYCHIC_03","PSYCHIC","SecondaryLevel",32,2,"PSYCHIC",0,null,true,true,true,"Active",76,"Level >= 32 AND SecondaryType = PSYCHIC","Secondary-type utility/defensive technique","OK"],
  ["LE_0367","MON_036|SK_ICE_01","MON_036","SP_GHOST_BEAST",2,"SK_ICE_01","ICE","SecondaryLevel",22,2,"ICE",0,null,true,true,true,"Active",82,"Level >= 22 AND SecondaryType = ICE","Secondary-type basic/offensive technique","OK"],
  ["LE_0368","MON_036|SK_ICE_03","MON_036","SP_GHOST_BEAST",2,"SK_ICE_03","ICE","SecondaryLevel",34,2,"ICE",0,null,true,true,true,"Active",76,"Level >= 34 AND SecondaryType = ICE","Secondary-type utility/defensive technique","OK"],
  ["LE_0369","MON_036|SK_PSYCHIC_04","MON_036","SP_GHOST_BEAST",2,"SK_PSYCHIC_04","PSYCHIC","Tutor",20,2,null,40,"TUTOR_TRICKSTER_1",false,true,true,"Active",69,"Level >= 20 AND Bond >= 40","Role tutor for Trickster build","OK"],
  ["LE_0370","MON_036|SK_DARK_02","MON_036","SP_GHOST_BEAST",2,"SK_DARK_02","DARK","Tutor",28,2,null,60,"TUTOR_TRICKSTER_2",false,true,true,"Active",68,"Level >= 28 AND Bond >= 60","Role tutor for Trickster build","OK"],
  ["LE_0371","MON_036|SK_PSYCHIC_02","MON_036","SP_GHOST_BEAST",2,"SK_PSYCHIC_02","PSYCHIC","BreedingCandidate",1,2,"PSYCHIC",0,"BREED_SP_GHOST_BEAST",false,true,true,"DataReady",50,"Egg inheritance candidate; target SecondaryType must allow PSYCHIC","BRD_v1.0 Skill Memory candidate; inherited from partner, not auto-equippable at hatch.","OK"],
  ["LE_0372","MON_036|SK_ICE_04","MON_036","SP_GHOST_BEAST",2,"SK_ICE_04","ICE","RareManual",30,2,"ICE",60,"MANUAL_SK_ICE_04",false,true,true,"Deferred",40,"Level >= 30 AND Bond >= 60 AND SecondaryType = ICE","Manual source becomes active after Item_Master Fix #12","OK"],
];

export const LEARNSET_CATALOG = Object.freeze(RAW_LEARNSET.map(([
  id, lookupKey, monsterId, speciesId, stage, skillId, sourceSkillType, method,
  learnLevel, requiredStage, requiredSourceSecondaryType, requiredBond, sourceId,
  autoLearn, relearnable, retainOnEvolution, state, priority, eligibilityRule, notes, integrity,
]) => Object.freeze({
  id,
  lookupKey,
  monsterId,
  speciesId,
  stage,
  skillId,
  sourceSkillType,
  method,
  learnLevel,
  requiredStage,
  requiredSourceSecondaryType,
  requiredRuntimeSecondaryType: requiredSourceSecondaryType ? TYPE_MAP[requiredSourceSecondaryType] : null,
  requiredBond,
  sourceId,
  autoLearn,
  relearnable,
  retainOnEvolution,
  state,
  priority,
  eligibilityRule,
  notes,
  integrity,
  rollout: state === 'Active' ? 'eligible_for_adapter' : 'blocked',
  activation: 'catalog_only',
  typeDecision: requiredSourceSecondaryType === 'LIGHT' ? 'D2_FAIRY_CANONICAL_LIGHT_DEFERRED' : 'D2_DIRECT_OR_NONE',
  sourceWorkbookVersion: CONTENT_PROVENANCE.workbookVersion,
})));

const KNOWN_MONSTER_IDS = new Set(MONSTER_CATALOG.flatMap(entry => [entry.workbookBaseMonsterId, entry.workbookStage2MonsterId]));
const ENTRY_BY_ID = new Map(LEARNSET_CATALOG.map(entry => [entry.id, entry]));
const EMPTY_ENTRIES = Object.freeze([]);
const ALL_BY_MONSTER = new Map();
const ACTIVE_BY_MONSTER = new Map();
for (const monsterId of KNOWN_MONSTER_IDS) {
  ALL_BY_MONSTER.set(monsterId, Object.freeze(LEARNSET_CATALOG.filter(entry => entry.monsterId === monsterId)));
  ACTIVE_BY_MONSTER.set(monsterId, Object.freeze(LEARNSET_CATALOG.filter(entry => entry.monsterId === monsterId && entry.state === 'Active')));
}
const RUNTIME_FIELDS = new Set(['learned', 'equippedSlot', 'masteryXp', 'currentUses', 'cooldownRemaining']);

function learnsetIssue(code, index, field, detail = {}) {
  return Object.freeze({ code, index, field, ...detail });
}

export function validateLearnsetCatalog(records) {
  if (!Array.isArray(records)) {
    return Object.freeze({ ok: false, issues: Object.freeze([learnsetIssue('invalid_catalog', -1, 'root')]) });
  }
  const issues = [];
  if (records.length !== 372) issues.push(learnsetIssue('learnset_count_mismatch', -1, 'length', { value: records.length }));
  const ids = new Set();
  const lookupKeys = new Set();
  records.forEach((entry, index) => {
    if (!entry || typeof entry !== 'object') {
      issues.push(learnsetIssue('invalid_entry', index, 'root'));
      return;
    }
    if (!/^LE_\d{4}$/.test(entry.id)) issues.push(learnsetIssue('invalid_entry_id', index, 'id', { id: entry.id ?? null }));
    if (ids.has(entry.id)) issues.push(learnsetIssue('duplicate_entry_id', index, 'id', { id: entry.id }));
    ids.add(entry.id);
    if (entry.lookupKey !== `${entry.monsterId}|${entry.skillId}`) issues.push(learnsetIssue('invalid_lookup_key', index, 'lookupKey'));
    if (lookupKeys.has(entry.lookupKey)) issues.push(learnsetIssue('duplicate_lookup_key', index, 'lookupKey', { key: entry.lookupKey }));
    lookupKeys.add(entry.lookupKey);
    if (!CONTENT_ID_PATTERNS.monsters.test(entry.monsterId) || !KNOWN_MONSTER_IDS.has(entry.monsterId)) issues.push(learnsetIssue('unknown_monster_reference', index, 'monsterId', { reference: entry.monsterId ?? null }));
    if (!CONTENT_ID_PATTERNS.skills.test(entry.skillId) || !skillCatalogEntry(entry.skillId)) issues.push(learnsetIssue('unknown_skill_reference', index, 'skillId', { reference: entry.skillId ?? null }));
    if (!LEARNSET_METHODS.includes(entry.method)) issues.push(learnsetIssue('invalid_method', index, 'method', { value: entry.method ?? null }));
    if (!CONTENT_STATES.includes(entry.state)) issues.push(learnsetIssue('invalid_state', index, 'state', { value: entry.state ?? null }));
    if (![1, 2].includes(entry.stage) || ![1, 2].includes(entry.requiredStage)) issues.push(learnsetIssue('invalid_stage', index, 'requiredStage'));
    if (!Number.isInteger(entry.learnLevel) || entry.learnLevel < 1 || entry.learnLevel > 100) issues.push(learnsetIssue('invalid_learn_level', index, 'learnLevel'));
    if (!Number.isInteger(entry.requiredBond) || entry.requiredBond < 0 || entry.requiredBond > 100) issues.push(learnsetIssue('invalid_required_bond', index, 'requiredBond'));
    if (entry.requiredSourceSecondaryType) {
      const expected = TYPE_MAP[entry.requiredSourceSecondaryType];
      if (!expected || entry.requiredRuntimeSecondaryType !== expected || entry.requiredRuntimeSecondaryType === 'Light') issues.push(learnsetIssue('invalid_secondary_type_mapping', index, 'requiredRuntimeSecondaryType'));
    } else if (entry.requiredRuntimeSecondaryType !== null) {
      issues.push(learnsetIssue('unexpected_secondary_type', index, 'requiredRuntimeSecondaryType'));
    }
    if (typeof entry.autoLearn !== 'boolean' || typeof entry.relearnable !== 'boolean' || typeof entry.retainOnEvolution !== 'boolean') issues.push(learnsetIssue('invalid_boolean_flag', index, 'autoLearn'));
    if (entry.integrity !== 'OK') issues.push(learnsetIssue('source_integrity_failed', index, 'integrity'));
    if (entry.activation !== 'catalog_only') issues.push(learnsetIssue('runtime_activation_forbidden', index, 'activation'));
    if (entry.state === 'Active' && entry.rollout !== 'eligible_for_adapter') issues.push(learnsetIssue('active_rollout_mismatch', index, 'rollout'));
    if (entry.state !== 'Active' && entry.rollout !== 'blocked') issues.push(learnsetIssue('blocked_content_activated', index, 'rollout'));
    if (entry.state !== 'Active' && entry.autoLearn) issues.push(learnsetIssue('blocked_content_auto_learn', index, 'autoLearn'));
    if (entry.requiredSourceSecondaryType === 'LIGHT' && (entry.requiredRuntimeSecondaryType !== 'Fairy' || entry.typeDecision !== 'D2_FAIRY_CANONICAL_LIGHT_DEFERRED')) issues.push(learnsetIssue('fairy_light_decision_missing', index, 'typeDecision'));
    for (const field of RUNTIME_FIELDS) {
      if (field in entry) issues.push(learnsetIssue('runtime_field_in_learnset', index, field));
    }
  });
  return Object.freeze({ ok: issues.length === 0, issues: Object.freeze(issues) });
}

export function learnsetEntryById(entryId) {
  return ENTRY_BY_ID.get(entryId) ?? null;
}

export function learnsetEntriesForMonster(monsterId, { includeBlocked = false } = {}) {
  return (includeBlocked ? ALL_BY_MONSTER : ACTIVE_BY_MONSTER).get(monsterId) ?? EMPTY_ENTRIES;
}
