import { claimMailbox, createTopupOrder, getMailbox, getMallProducts, getWallet, purchaseMallProduct } from './server-sync.mjs';

const money=n=>Number(n||0).toLocaleString('th-TH');
export function initializeMallUI(){
  if(document.getElementById('mallToggle'))return;
  document.body.insertAdjacentHTML('beforeend',`<button id="mallToggle" class="mall-toggle">🛒<span>มอลล์</span></button><section id="mallPanel" class="mall-panel hidden"><header><b>🛒 ITEM MALL</b><div class="mall-wallet"><span id="mallCash">💎 0</span><span id="mallBonus">🎟 0</span></div><button id="mallClose">×</button></header><nav><button data-mall-tab="products" class="active">สินค้า</button><button data-mall-tab="topup">เติมเงิน</button><button data-mall-tab="mailbox">กล่องจดหมาย</button></nav><div id="mallContent" class="mall-content"></div><div id="mallStatus" class="mall-status"></div></section>`);
  const panel=document.getElementById('mallPanel'),content=document.getElementById('mallContent'),status=document.getElementById('mallStatus');let tab='products';
  const updateWallet=async()=>{const w=await getWallet();if(!w)return;document.getElementById('mallCash').textContent=`💎 ${money(w.cashBalance)}`;document.getElementById('mallBonus').textContent=`🎟 ${money(w.bonusBalance)}`;};
  const renderProducts=async()=>{content.innerHTML='<p class="mall-loading">กำลังโหลดสินค้า…</p>';const products=await getMallProducts();content.innerHTML=products.map(p=>`<article class="mall-product"><div class="mall-product-icon">${p.category==='VIP'?'♛':p.category==='PACKAGE'?'🎁':'⚗'}</div><div><b>${p.name}</b><p>${p.description}</p><small>ได้รับ ${p.itemId} × ${p.quantity}${p.purchaseLimit?` • จำกัด ${p.purchaseLimit} ครั้ง`:''}</small></div><div class="mall-buy">${p.cashPrice?`<button data-buy="${p.id}" data-currency="CASH">💎 ${money(p.cashPrice)}</button>`:''}${p.bonusPrice?`<button data-buy="${p.id}" data-currency="BONUS" class="bonus">🎟 ${money(p.bonusPrice)}</button>`:''}</div></article>`).join('')||'<p class="mall-loading">ยังไม่มีสินค้า</p>';content.querySelectorAll('[data-buy]').forEach(button=>button.onclick=async()=>{if(!confirm(`ยืนยันซื้อสินค้านี้ด้วย ${button.dataset.currency} Point?`))return;button.disabled=true;const result=await purchaseMallProduct(button.dataset.buy,button.dataset.currency);status.textContent=result.message;status.className=`mall-status ${result.ok?'ok':'error'}`;await updateWallet();button.disabled=false;});};
  const renderTopup=()=>{content.innerHTML=`<div class="topup-note"><b>Sandbox Payment</b><p>สร้าง Order แล้วให้ GM ยืนยันใน Server Manager ระบบจึงเพิ่ม Cash Point</p></div><div class="topup-grid">${[[2000,20],[5000,55],[10000,120],[30000,380],[50000,650]].map(([satang,points])=>`<button data-topup="${satang}" data-points="${points}"><b>${satang/100} บาท</b><span>💎 ${points} Cash Point</span></button>`).join('')}</div>`;content.querySelectorAll('[data-topup]').forEach(button=>button.onclick=async()=>{button.disabled=true;const result=await createTopupOrder(Number(button.dataset.topup),Number(button.dataset.points));status.textContent=result.message+(result.order?` • Order ${result.order.orderId}`:'');status.className=`mall-status ${result.ok?'ok':'error'}`;button.disabled=false;});};
  const renderMailbox=async()=>{content.innerHTML='<p class="mall-loading">กำลังโหลดกล่องจดหมาย…</p>';const deliveries=await getMailbox();content.innerHTML=deliveries.map(d=>`<article class="mail-row"><div><b>${d.itemId} × ${d.quantity}</b><small>Order ${d.orderId.slice(0,8)} • ${d.status}</small></div>${d.status==='PENDING'?`<button data-claim="${d.id}">รับของ</button>`:'<span>✓ รับแล้ว</span>'}</article>`).join('')||'<p class="mall-loading">ไม่พบของในกล่องจดหมาย</p>';content.querySelectorAll('[data-claim]').forEach(button=>button.onclick=async()=>{button.disabled=true;const result=await claimMailbox(button.dataset.claim);status.textContent=result.message;status.className=`mall-status ${result.ok?'ok':'error'}`;if(result.ok)window.dispatchEvent(new CustomEvent('monsterlife-inventory-update',{detail:result}));await renderMailbox();});};
  const render=async()=>{status.textContent='';await updateWallet();if(tab==='products')await renderProducts();else if(tab==='topup')renderTopup();else await renderMailbox();};
  document.getElementById('mallToggle').onclick=()=>{panel.classList.remove('hidden');render();};document.getElementById('mallClose').onclick=()=>panel.classList.add('hidden');panel.querySelectorAll('[data-mall-tab]').forEach(button=>button.onclick=()=>{tab=button.dataset.mallTab;panel.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===button));render();});
}
