import assert from 'node:assert/strict';
import { RUNTIME_TYPES } from '../type-catalog.mjs';
import { activeHtml as html, activeJs as js } from './active-assets.mjs';
const must=(needle,msg)=>assert.ok(js.includes(needle),msg||`missing ${needle}`);

// Ring 0 / Ring 1 static contract guards
assert.ok(!html.includes('id="attackBtn"'),'player attack button must not be a primary damage source');
assert.ok(!js.includes('function playerAttack'),'player direct attack implementation must stay removed');
must('RANCH_ACTIVE_MAX=6','Ranch rendered cap must remain 6');
must("targetType:'enemy'"); must("targetType:'area'"); must("targetType:'self'");
must("if(activeSummon){msg('ต้อง Recall มอนของเราก่อนเข้าสู่ Capture Aim')",'capture must be blocked while owned monster is active');
must('beginCaptureAttempt(captureAttemptLedger','a real throw attempt must consume through the transaction');
assert.doesNotMatch(js,/captureBalls\s*--|captureBalls\s*-=\s*1/,'scene code must not consume capture balls outside the transaction');
must('captureWorkbookVariant(w)','boss/elite capture variants must enter the workbook resolver');
must('resolveWorkbookCapture(input)','live capture coefficients must come from CAP_v1.0');
must('commitCaptureAttempt(captureAttemptLedger','capture completion must be idempotent');
must('function resetWild(w,cause=','wild encounter reset with an observable cause must exist');
must('inst.fainted=true','Fainted state must exist');
must('faintActive()','Fainted auto recall path must exist');
must('evaluateStandardBreedingCompatibility(roles.eggHolder,roles.partner','breeding enters the canonical Stage2/Level/Bond/gender/group gate');
must('createStandardBreedingEggTransaction(state','offspring is snapshotted by the canonical egg transaction');
must('hatchBreedingEggTransaction(state','hatching enters the idempotent canonical transaction');
must('workbookBreedingProfile(holder?.speciesId)','live offspring preview uses the canonical egg-holder family');
must('if(!confirm(`Evolution ย้อนกลับไม่ได้','evolution must confirm irreversibility');
must("hub:{label:'Ranch Hub'"); must("grassland:{label:'Green Meadow'"); must("cave:{label:'Echo Cave'");
const expected=['flameling','mossbun','voltkit','aquapuff','frostowl','ironbug','emberdrake','voidhorn'];
for(const id of expected) must(`id:'${id}'`,`missing vertical slice species ${id}`);
assert.equal(RUNTIME_TYPES.length,18,'type baseline must contain 18 types');
assert.equal(new Set(RUNTIME_TYPES).size,18,'type baseline identities must stay unique');
assert.ok(RUNTIME_TYPES.includes('Fairy'),'Fairy must remain the canonical runtime type');
assert.ok(!RUNTIME_TYPES.includes('Light'),'Light must not become a second runtime type');
console.log('Active Ring 0 + Ring 1 static regression: PASS');
